--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "USER06279"."ALUMNO" DROP CONSTRAINT "COLEGIO_ALUMNO_FK";

ALTER TABLE "USER06279"."ALUMNO" DROP CONSTRAINT "PERSONA_ALUMNO_FK";

ALTER TABLE "USER06279"."ALUMNO_APODERADO" DROP CONSTRAINT "ALUMNO_ALUMNO_APODERADO_FK";

ALTER TABLE "USER06279"."ALUMNO_APODERADO" DROP CONSTRAINT "APODERADO_ALUMNO_APODERADO_FK";

ALTER TABLE "USER06279"."APODERADO" DROP CONSTRAINT "PERSONA_APODERADO_FK";

ALTER TABLE "USER06279"."APODERADO" DROP CONSTRAINT "TIPO_APODERADO_APODERADO_FK";

ALTER TABLE "USER06279"."ASIGNACION" DROP CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_ASIGNACIONES_FK";

ALTER TABLE "USER06279"."ASIGNACION" DROP CONSTRAINT "TIPO_ASIGNACION_ASIGNACIONES_FK";

ALTER TABLE "USER06279"."ASIGNACION_ALUMNO" DROP CONSTRAINT "ALUMNO_ASIGNACION_ALUMNO_FK";

ALTER TABLE "USER06279"."ASIGNACION_ALUMNO" DROP CONSTRAINT "ASIGNACIONES_ASIGNACION_ALUMNO_FK";

ALTER TABLE "USER06279"."ASISTENCIA" DROP CONSTRAINT "ALUMNO_ASISTENCIA_FK";

ALTER TABLE "USER06279"."ASISTENCIA" DROP CONSTRAINT "CURSO_ASISTENCIA_FK";

ALTER TABLE "USER06279"."ASISTENCIA" DROP CONSTRAINT "JUSTIFICACION_ASISTENCIA_FK";

ALTER TABLE "USER06279"."ASISTENCIA" DROP CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_ASISTENCIA_FK";

ALTER TABLE "USER06279"."AVISO" DROP CONSTRAINT "COLEGIO_ACTIVIDAD_FK";

ALTER TABLE "USER06279"."AVISO_SECCION" DROP CONSTRAINT "ACTIVIDAD_ACTIVIDAD_SECCION_FK";

ALTER TABLE "USER06279"."AVISO_SECCION" DROP CONSTRAINT "SECCION_ACTIVIDAD_SECCION_FK";

ALTER TABLE "USER06279"."COLEGIO_MEDIO_CONTACTO" DROP CONSTRAINT "COLEGIO_COLEGIO_MEDIO_CONTACTO_FK";

ALTER TABLE "USER06279"."COLEGIO_MEDIO_CONTACTO" DROP CONSTRAINT "MEDIO_CONTACTO_COLEGIO_MEDIO_CONTACTO_FK";

ALTER TABLE "USER06279"."CONCEPTO" DROP CONSTRAINT "COLEGIO_CONCEPTO_FK";

ALTER TABLE "USER06279"."CUENTA_BANCO" DROP CONSTRAINT "BANCO_CUENTA_BANCO_FK";

ALTER TABLE "USER06279"."CUENTA_BANCO" DROP CONSTRAINT "COLEGIO_BANCO_FK";

ALTER TABLE "USER06279"."CURSO" DROP CONSTRAINT "COLEGIO_CURSO_FK";

ALTER TABLE "USER06279"."CURSO_GRADO" DROP CONSTRAINT "CURSO_CURSO_GRADO_FK";

ALTER TABLE "USER06279"."CURSO_GRADO" DROP CONSTRAINT "GRADO_CURSO_GRADO_FK";

ALTER TABLE "USER06279"."DOCENTE" DROP CONSTRAINT "COLEGIO_DOCENTE_FK";

ALTER TABLE "USER06279"."DOCENTE" DROP CONSTRAINT "PERSONA_DOCENTE_FK";

ALTER TABLE "USER06279"."EVALUACION" DROP CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_EVALUACION_FK";

ALTER TABLE "USER06279"."EVALUACION" DROP CONSTRAINT "TIPO_EVALUACION_EVALUACION_FK";

ALTER TABLE "USER06279"."EVALUACION_ALUMNO" DROP CONSTRAINT "ALUMNO_EVALUACION_ALUMNO_FK";

ALTER TABLE "USER06279"."EVALUACION_ALUMNO" DROP CONSTRAINT "EVALUACION_EVALUACION_ALUMNO_FK";

ALTER TABLE "USER06279"."FOTO_PERSONA" DROP CONSTRAINT "PERSONA_FOTO_FK";

ALTER TABLE "USER06279"."FOTO_PERSONA" DROP CONSTRAINT "REPOSITORIO_ARCHIVOS_FOTO_PERSONA_FK";

ALTER TABLE "USER06279"."GRADO" DROP CONSTRAINT "COLEGIO_GRADO_FK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS" DROP CONSTRAINT "ALUMNO_LIBRETA_NOTAS_FK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS" DROP CONSTRAINT "PERIODO_ACADEMICO_SECCION_LIBRETA_NOTAS_FK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS" DROP CONSTRAINT "SECCION_LIBRETA_NOTAS_FK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS_FINALES_CURSO" DROP CONSTRAINT "CURSO_LIBRETA_NOTAS_FINALES_CURSO_FK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS_FINALES_CURSO" DROP CONSTRAINT "LIBRETA_NOTAS_LIBRETA_NOTAS_FINALES_FK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS_FINALES_CURSO" DROP CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_LIBRETA_NOTAS_FINALES_CURSO_FK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS_SUBPERIODO" DROP CONSTRAINT "CURSO_LIBRETA_NOTAS_SUBPERIODO_FK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS_SUBPERIODO" DROP CONSTRAINT "LIBRETA_NOTAS_LIBRETA_NOTAS_SUBPERIODO_FK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS_SUBPERIODO" DROP CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_LIBRETA_NOTAS_SUBPERIODO_FK";

ALTER TABLE "USER06279"."MATERIALES" DROP CONSTRAINT "REPOSITORIO_ARCHIVOS_MATERIALES_FK";

ALTER TABLE "USER06279"."MATERIAL_ASIGNACION" DROP CONSTRAINT "ASIGNACIONES_MATERIAL_EVALUACION_FK";

ALTER TABLE "USER06279"."MATERIAL_ASIGNACION" DROP CONSTRAINT "MATERIALES_MATERIAL_EVALUACION_FK1";

ALTER TABLE "USER06279"."MATERIAL_EVALUACION" DROP CONSTRAINT "EVALUACION_MATERIAL_EVALUACION_FK";

ALTER TABLE "USER06279"."MATERIAL_EVALUACION" DROP CONSTRAINT "MATERIALES_MATERIAL_EVALUACION_FK";

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_PERIODO" DROP CONSTRAINT "MATERIALES_MATERIAL_SECCION_CURSO_PERIODO_FK";

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_PERIODO" DROP CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_MATERIAL_SECCION_CURSO_PERIO950";

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_SUB_PERIODO" DROP CONSTRAINT "MATERIALES_MATERIAL_SECCION_CURSO_SUB_PERIODO_FK";

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_SUB_PERIODO" DROP CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_MATERIAL_SECCION_CURSO_S478";

ALTER TABLE "USER06279"."MATRICULA_ALUMNO" DROP CONSTRAINT "ALUMNO_MATRICULA_ALUMNO_FK";

ALTER TABLE "USER06279"."MATRICULA_ALUMNO" DROP CONSTRAINT "PERIODO_ACADEMICO_SECCION_MATRICULA_ALUMNO_FK";

ALTER TABLE "USER06279"."MENSAJE" DROP CONSTRAINT "MENSAJE_MENSAJE_FK";

ALTER TABLE "USER06279"."MENSAJE" DROP CONSTRAINT "PERSONA_MENSAJE_FK";

ALTER TABLE "USER06279"."MENSAJE_DESTINATARIO" DROP CONSTRAINT "MENSAJE_MENSAJE_DESTINATARIO_FK";

ALTER TABLE "USER06279"."MENSAJE_DESTINATARIO" DROP CONSTRAINT "PERSONA_MENSAJE_DESTINATARIO_FK";

ALTER TABLE "USER06279"."MONEDA_COLEGIO" DROP CONSTRAINT "COLEGIO_MONEDA_FK";

ALTER TABLE "USER06279"."MONEDA_COLEGIO" DROP CONSTRAINT "MONEDA_MONEDA_COLEGIO_FK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO" DROP CONSTRAINT "COLEGIO_PERIODO_ACADEMICO_FK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO" DROP CONSTRAINT "PERIODO_ACADEMICO_PERIODO_ACADEMICO_FK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION" DROP CONSTRAINT "SECCION_PERIODO_ACADEMICO_SECCION_FK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO" DROP CONSTRAINT "CURSO_SECCION_CURSO_FK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO" DROP CONSTRAINT "DOCENTE_PERIODO_ACADEMICO_SECCION_CURSO_FK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO" DROP CONSTRAINT "PERIODO_ACADEMICO_SECCION_PERIODO_ACADEMICO_SECCION_CURSO_FK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO" DROP CONSTRAINT "SECCION_PERIODO_ACADEMICO_SECCION_CURSO_FK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO_NOTA" DROP CONSTRAINT "ALUMNO_PERIODO_ACADEMICO_SECCION_CURSO_ALUMNO_FK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO_NOTA" DROP CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_PERIODO_ACADEMICO_SECCION_CU584";

ALTER TABLE "USER06279"."PERMISO" DROP CONSTRAINT "PERSONA_PERMISO_FK";

ALTER TABLE "USER06279"."PERMISO" DROP CONSTRAINT "PERSONA_PERMISO_FK1";

ALTER TABLE "USER06279"."PERSONA_MEDIO_CONTACTO" DROP CONSTRAINT "MEDIO_CONTACTO_PERSONA_MEDIO_CONTACTO_FK";

ALTER TABLE "USER06279"."PERSONA_MEDIO_CONTACTO" DROP CONSTRAINT "PERSONA_PERSONA_MEDIO_CONTACTO_FK";

ALTER TABLE "USER06279"."RECIBO_PENSION" DROP CONSTRAINT "ALUMNO_RECIBO_PENSION_FK";

ALTER TABLE "USER06279"."RECIBO_PENSION" DROP CONSTRAINT "BANCO_RECIBO_PENSION_FK";

ALTER TABLE "USER06279"."RECIBO_PENSION" DROP CONSTRAINT "MONEDA_RECIBO_PENSION_FK";

ALTER TABLE "USER06279"."RECIBO_PENSION_DETALLE" DROP CONSTRAINT "CONCEPTO_RECIBO_PENSION_DETALLE_FK";

ALTER TABLE "USER06279"."RECIBO_PENSION_DETALLE" DROP CONSTRAINT "RECIBO_PENSION_RECIBO_PENSION_DETALLE_FK";

ALTER TABLE "USER06279"."REPOSITORIO_ARCHIVOS" DROP CONSTRAINT "COLEGIO_REPOSITORIO_ARCHIVOS_FK";

ALTER TABLE "USER06279"."RESUMEN_ALUMNO" DROP CONSTRAINT "ALUMNO_RESUMEN_ALUMNO_FK";

ALTER TABLE "USER06279"."RESUMEN_ALUMNO" DROP CONSTRAINT "COLEGIO_RESUMEN_ALUMNO_FK";

ALTER TABLE "USER06279"."RESUMEN_ALUMNO" DROP CONSTRAINT "GRADO_RESUMEN_ALUMNO_FK";

ALTER TABLE "USER06279"."RESUMEN_ALUMNO" DROP CONSTRAINT "SECCION_RESUMEN_ALUMNO_FK";

ALTER TABLE "USER06279"."SECCION" DROP CONSTRAINT "COLEGIO_SECCION_FK";

ALTER TABLE "USER06279"."SECCION" DROP CONSTRAINT "GRADO_SECCION_FK";

ALTER TABLE "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO" DROP CONSTRAINT "CURSO_SUB_PERIODO_ACADEMICO_SECCION_CURSO_FK";

ALTER TABLE "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO" DROP CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_SUB_PERIODO_ACADEMICO_SECCIO60";

ALTER TABLE "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO" DROP CONSTRAINT "SECCION_SUB_PERIODO_ACADEMICO_SECCION_CURSO_FK";

ALTER TABLE "USER06279"."TIPO_ASIGNACION" DROP CONSTRAINT "COLEGIO_TIPO_ASIGNACION_FK";

ALTER TABLE "USER06279"."TIPO_EVALUACION" DROP CONSTRAINT "COLEGIO_TIPO_EVALUACION_FK";

ALTER TABLE "USER06279"."ALUMNO" DROP CONSTRAINT "ALUMNO_PK";

ALTER TABLE "USER06279"."ALUMNO_APODERADO" DROP CONSTRAINT "ALUMNO_APODERADO_PK";

ALTER TABLE "USER06279"."APODERADO" DROP CONSTRAINT "APODERADO_PK";

ALTER TABLE "USER06279"."ASIGNACION" DROP CONSTRAINT "ASIGNACION_PK";

ALTER TABLE "USER06279"."ASIGNACION_ALUMNO" DROP CONSTRAINT "ASIGNACION_ALUMNO_PK";

ALTER TABLE "USER06279"."ASISTENCIA" DROP CONSTRAINT "ASISTENCIA_PK";

ALTER TABLE "USER06279"."AVISO" DROP CONSTRAINT "AVISO_PK";

ALTER TABLE "USER06279"."BANCO" DROP CONSTRAINT "BANCO_PK";

ALTER TABLE "USER06279"."COLEGIO" DROP CONSTRAINT "COLEGIO_PK";

ALTER TABLE "USER06279"."COLEGIO_MEDIO_CONTACTO" DROP CONSTRAINT "COLEGIO_MEDIO_CONTACTO_PK";

ALTER TABLE "USER06279"."CONCEPTO" DROP CONSTRAINT "CONCEPTO_PK";

ALTER TABLE "USER06279"."CUENTA_BANCO" DROP CONSTRAINT "CUENTA_BANCO_PK";

ALTER TABLE "USER06279"."CURSO" DROP CONSTRAINT "CURSO_PK";

ALTER TABLE "USER06279"."CURSO_GRADO" DROP CONSTRAINT "CURSO_GRADO_PK";

ALTER TABLE "USER06279"."DOCENTE" DROP CONSTRAINT "DOCENTE_PK";

ALTER TABLE "USER06279"."EVALUACION" DROP CONSTRAINT "EVALUACION_PK";

ALTER TABLE "USER06279"."EVALUACION_ALUMNO" DROP CONSTRAINT "EVALUACION_ALUMNO_PK";

ALTER TABLE "USER06279"."FOTO_PERSONA" DROP CONSTRAINT "FOTO_PERSONA_PK";

ALTER TABLE "USER06279"."GRADO" DROP CONSTRAINT "GRADO_PK";

ALTER TABLE "USER06279"."JUSTIFICACION" DROP CONSTRAINT "JUSTIFICACION_PK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS" DROP CONSTRAINT "LIBRETA_NOTAS_PK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS_FINALES_CURSO" DROP CONSTRAINT "LIBRETA_NOTAS_FINALES_CURSO_PK";

ALTER TABLE "USER06279"."LIBRETA_NOTAS_SUBPERIODO" DROP CONSTRAINT "LIBRETA_NOTAS_SUBPERIODO_PK";

ALTER TABLE "USER06279"."MATERIALES" DROP CONSTRAINT "MATERIALES_PK";

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_PERIODO" DROP CONSTRAINT "MATERIAL_SECCION_CURSO_PERIODO_PK";

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_SUB_PERIODO" DROP CONSTRAINT "MATERIAL_SECCION_CURSO_SUB_PERIODO_PK";

ALTER TABLE "USER06279"."MATRICULA_ALUMNO" DROP CONSTRAINT "MATRICULA_ALUMNO_PK";

ALTER TABLE "USER06279"."MEDIO_CONTACTO" DROP CONSTRAINT "MEDIO_CONTACTO_PK";

ALTER TABLE "USER06279"."MENSAJE" DROP CONSTRAINT "MENSAJE_PK";

ALTER TABLE "USER06279"."MONEDA" DROP CONSTRAINT "MONEDA_PK";

ALTER TABLE "USER06279"."MONEDA_COLEGIO" DROP CONSTRAINT "MONEDA_COLEGIO_PK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO" DROP CONSTRAINT "PERIODO_ACADEMICO_PK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION" DROP CONSTRAINT "PERIODO_ACADEMICO_SECCION_PK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO" DROP CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_PK";

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO_NOTA" DROP CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_NOTA_PK";

ALTER TABLE "USER06279"."PERMISO" DROP CONSTRAINT "PERMISO_PK";

ALTER TABLE "USER06279"."PERSONA" DROP CONSTRAINT "PERSONA_PK";

ALTER TABLE "USER06279"."PERSONA_MEDIO_CONTACTO" DROP CONSTRAINT "PERSONA_MEDIO_CONTACTO_PK";

ALTER TABLE "USER06279"."RECIBO_PENSION" DROP CONSTRAINT "RECIBO_PENSION_PK";

ALTER TABLE "USER06279"."RECIBO_PENSION_DETALLE" DROP CONSTRAINT "RECIBO_PENSION_DETALLE_PK";

ALTER TABLE "USER06279"."REPOSITORIO_ARCHIVOS" DROP CONSTRAINT "REPOSITORIO_ARCHIVOS_PK";

ALTER TABLE "USER06279"."RESUMEN_ALUMNO" DROP CONSTRAINT "RESUMEN_ALUMNO_PK";

ALTER TABLE "USER06279"."SECCION" DROP CONSTRAINT "SECCION_PK";

ALTER TABLE "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO" DROP CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_PK";

ALTER TABLE "USER06279"."TIPO_APODERADO" DROP CONSTRAINT "TIPO_APODERADO_PK";

ALTER TABLE "USER06279"."TIPO_ASIGNACION" DROP CONSTRAINT "TIPO_ASIGNACION_PK";

ALTER TABLE "USER06279"."TIPO_EVALUACION" DROP CONSTRAINT "TIPO_EVALUACION_PK";

DROP TABLE "USER06279"."ALUMNO";

DROP TABLE "USER06279"."ALUMNO_APODERADO";

DROP TABLE "USER06279"."APODERADO";

DROP TABLE "USER06279"."ASIGNACION";

DROP TABLE "USER06279"."ASIGNACION_ALUMNO";

DROP TABLE "USER06279"."ASISTENCIA";

DROP TABLE "USER06279"."AVISO";

DROP TABLE "USER06279"."AVISO_SECCION";

DROP TABLE "USER06279"."BANCO";

DROP TABLE "USER06279"."COLEGIO";

DROP TABLE "USER06279"."COLEGIO_MEDIO_CONTACTO";

DROP TABLE "USER06279"."CONCEPTO";

DROP TABLE "USER06279"."CUENTA_BANCO";

DROP TABLE "USER06279"."CURSO";

DROP TABLE "USER06279"."CURSO_GRADO";

DROP TABLE "USER06279"."DOCENTE";

DROP TABLE "USER06279"."EVALUACION";

DROP TABLE "USER06279"."EVALUACION_ALUMNO";

DROP TABLE "USER06279"."FOTO_PERSONA";

DROP TABLE "USER06279"."GRADO";

DROP TABLE "USER06279"."JUSTIFICACION";

DROP TABLE "USER06279"."LIBRETA_NOTAS";

DROP TABLE "USER06279"."LIBRETA_NOTAS_FINALES_CURSO";

DROP TABLE "USER06279"."LIBRETA_NOTAS_SUBPERIODO";

DROP TABLE "USER06279"."MATERIALES";

DROP TABLE "USER06279"."MATERIAL_ASIGNACION";

DROP TABLE "USER06279"."MATERIAL_EVALUACION";

DROP TABLE "USER06279"."MATERIAL_SECCION_CURSO_PERIODO";

DROP TABLE "USER06279"."MATERIAL_SECCION_CURSO_SUB_PERIODO";

DROP TABLE "USER06279"."MATRICULA_ALUMNO";

DROP TABLE "USER06279"."MEDIO_CONTACTO";

DROP TABLE "USER06279"."MENSAJE";

DROP TABLE "USER06279"."MENSAJE_DESTINATARIO";

DROP TABLE "USER06279"."MONEDA";

DROP TABLE "USER06279"."MONEDA_COLEGIO";

DROP TABLE "USER06279"."PERIODO_ACADEMICO";

DROP TABLE "USER06279"."PERIODO_ACADEMICO_SECCION";

DROP TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO";

DROP TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO_NOTA";

DROP TABLE "USER06279"."PERMISO";

DROP TABLE "USER06279"."PERSONA";

DROP TABLE "USER06279"."PERSONA_MEDIO_CONTACTO";

DROP TABLE "USER06279"."RECIBO_PENSION";

DROP TABLE "USER06279"."RECIBO_PENSION_DETALLE";

DROP TABLE "USER06279"."REPOSITORIO_ARCHIVOS";

DROP TABLE "USER06279"."RESUMEN_ALUMNO";

DROP TABLE "USER06279"."SECCION";

DROP TABLE "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO";

DROP TABLE "USER06279"."TIPO_APODERADO";

DROP TABLE "USER06279"."TIPO_ASIGNACION";

DROP TABLE "USER06279"."TIPO_EVALUACION";

DROP SCHEMA "USER06279" RESTRICT;

CREATE SCHEMA "USER06279" AUTHORIZATION "USER06279";

CREATE TABLE "USER06279"."ALUMNO" (
		"ID_PERSONA" BIGINT NOT NULL,
		"ID_COLEGIO" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."ALUMNO_APODERADO" (
		"ID_PERSONA_APODERADO" BIGINT NOT NULL,
		"ID_PERSONA_ALUMNO" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."APODERADO" (
		"ID_PERSONA" BIGINT NOT NULL,
		"ID_TIPO_APODERADO" SMALLINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."ASIGNACION" (
		"ID_ASIGNACION" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO" BIGINT NOT NULL,
		"ID_TIPO_ASIGNACION" SMALLINT NOT NULL,
		"DESCRIPCION" VARCHAR(32600) NOT NULL,
		"FECHA_ENTREGA" DATE NOT NULL,
		"ETIQUETA" VARCHAR(2) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."ASIGNACION_ALUMNO" (
		"ID_ASIGNACION_ALUMNO" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_ASIGNACION" BIGINT NOT NULL,
		"ID_ALUMNO" BIGINT NOT NULL,
		"NOTA" DECIMAL(2 , 2),
		"ID_SUB_PERIODO" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."ASISTENCIA" (
		"ID_ASISTENCIA" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO" BIGINT NOT NULL,
		"ID_SUB_PERIODO_ACADEMICO" BIGINT NOT NULL,
		"ID_CURSO" INTEGER NOT NULL,
		"ID_ALUMNO" BIGINT NOT NULL,
		"FECHA" DATE NOT NULL,
		"ASISTIO" CHAR(1) NOT NULL,
		"JUSTIFICADA" CHAR(1) NOT NULL DEFAULT '0',
		"ID_JUSTIFICACION" SMALLINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."AVISO" (
		"ID_AVISO" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"NOMBRE" VARCHAR(40) NOT NULL,
		"ID_COLEGIO" BIGINT NOT NULL,
		"DESCRIPCION" VARCHAR(500) NOT NULL,
		"LUGAR" VARCHAR(100) NOT NULL,
		"ID_SUB_PERIODO_ACADEMICO" BIGINT NOT NULL,
		"FECHA_FIN_PUBLICACION" DATE NOT NULL,
		"FECHA_INICIO_PUBLICACION" DATE NOT NULL,
		"GENERAL" CHAR(1) NOT NULL DEFAULT '0'
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."AVISO_SECCION" (
		"ID_AVISO" BIGINT NOT NULL,
		"ID_SECCION" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."BANCO" (
		"ID_BANCO" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 NO CYCLE CACHE 20),
		"NOMBRE" VARCHAR(40) NOT NULL,
		"ABREVIATURA" VARCHAR(10) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."COLEGIO" (
		"ID_COLEGIO" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"CODIGO" VARCHAR(32600),
		"DIRECCION" VARCHAR(32600) NOT NULL,
		"NOMBRE" VARCHAR(32600) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."COLEGIO_MEDIO_CONTACTO" (
		"ID_COLEGIO" BIGINT NOT NULL,
		"ID_MEDIO_CONTACTO" INTEGER NOT NULL,
		"REFERENCIA" VARCHAR(32600) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."CONCEPTO" (
		"ID_CONCEPTO" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20),
		"ID_COLEGIO" BIGINT NOT NULL,
		"NOMBRE" VARCHAR(100) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."CUENTA_BANCO" (
		"ID_BANCO" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 NO CYCLE CACHE 20),
		"ID_COLEGIO" BIGINT NOT NULL,
		"NUMERO" VARCHAR(25) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."CURSO" (
		"ID_CURSO" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20),
		"NOMBRE" VARCHAR(50) NOT NULL,
		"ID_COLEGIO" BIGINT NOT NULL,
		"VIGENTE" CHAR(1) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."CURSO_GRADO" (
		"ID_CURSO" INTEGER NOT NULL,
		"ID_GRADO" INTEGER NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."DOCENTE" (
		"ID_PERSONA" BIGINT NOT NULL,
		"ID_COLEGIO" BIGINT NOT NULL DEFAULT 1
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."EVALUACION" (
		"ID_EVALUACION" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO" BIGINT NOT NULL,
		"ID_TIPO_EVALUACION" INTEGER NOT NULL,
		"FECHA_PROGRAMADA" DATE NOT NULL,
		"ETIQUETA" VARCHAR(2) NOT NULL,
		"FECHA_EVALUACION" DATE
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."EVALUACION_ALUMNO" (
		"ID_EVALUACION_ALUMNO" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_ALUMNO" BIGINT NOT NULL,
		"FECHA_INGRESO" DATE NOT NULL,
		"ID_EVALUACION" BIGINT NOT NULL,
		"NOTA" DECIMAL(2 , 2) NOT NULL,
		"ID_SUB_PERIODO" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."FOTO_PERSONA" (
		"ID_FOTO" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_PERSONA" BIGINT NOT NULL,
		"ID_REPOSITORIO" INTEGER NOT NULL,
		"VIGENTE" CHAR(1) NOT NULL,
		"NOMBRE_ARCHIVO" VARCHAR(20) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."GRADO" (
		"ID_GRADO" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20),
		"CORRELATIVO" INTEGER NOT NULL,
		"NOMBRE" VARCHAR(32600) NOT NULL,
		"ETIQUETA" VARCHAR(6) NOT NULL,
		"ID_COLEGIO" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."JUSTIFICACION" (
		"ID_JUSTIFICACION" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 NO CYCLE CACHE 20),
		"TIPO_JUSTIFICACION" VARCHAR(20) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."LIBRETA_NOTAS" (
		"ID_LIBRETA_NOTAS" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_PERIODO_ACADEMICO_SECCION" BIGINT NOT NULL,
		"ID_SECCION" BIGINT NOT NULL,
		"ID_ALUMNO" BIGINT NOT NULL,
		"ID_PERIODO_ACADEMICO" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."LIBRETA_NOTAS_FINALES_CURSO" (
		"ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_CURSO" INTEGER NOT NULL,
		"ID_LIBRETA_NOTAS" BIGINT NOT NULL,
		"NOTA" DECIMAL(4 , 2) NOT NULL,
		"ID_PERIODO_ACADEMICO_SECCION_CURSO" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."LIBRETA_NOTAS_SUBPERIODO" (
		"ID_LIBRETA_NOTAS_SUBPERIODO" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_CURSO" INTEGER NOT NULL,
		"NOTA" DECIMAL(4 , 2) NOT NULL,
		"ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO" BIGINT NOT NULL,
		"ID_LIBRETA_NOTAS" BIGINT NOT NULL,
		"ID_SUB_PERIODO" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."MATERIALES" (
		"ID_MATERIAL" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_REPOSITORIO" INTEGER NOT NULL,
		"NOMBRE_ARCHIVO" VARCHAR(50) NOT NULL,
		"DESCRIPCION" VARCHAR(100) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."MATERIAL_ASIGNACION" (
		"ID_MATERIAL" BIGINT NOT NULL,
		"ID_ASIGNACION" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."MATERIAL_EVALUACION" (
		"ID_MATERIAL" BIGINT NOT NULL,
		"ID_EVALUACION" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."MATERIAL_SECCION_CURSO_PERIODO" (
		"ID_PERIODO_ACADEMICO_SECCION_CURSO" BIGINT NOT NULL,
		"ID_MATERIAL" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."MATERIAL_SECCION_CURSO_SUB_PERIODO" (
		"ID_MATERIAL" BIGINT NOT NULL,
		"ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."MATRICULA_ALUMNO" (
		"ID_MATRICULA" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"USUARIO" VARCHAR(25) NOT NULL,
		"ID_ALUMNO" BIGINT NOT NULL,
		"FECHA" DATE NOT NULL,
		"ID_PERIODO_ACADEMICO_SECCION" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."MEDIO_CONTACTO" (
		"ID_MEDIO_CONTACTO" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20),
		"NOMBRE" VARCHAR(32600) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."MENSAJE" (
		"ID_MENSAJE" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"MENSAJE" VARCHAR(32600) NOT NULL,
		"ID_PERSONA_FROM" BIGINT NOT NULL,
		"FECHA" DATE NOT NULL,
		"ASUNTO" VARCHAR(50) NOT NULL,
		"PARENT_ID_MENSAJE" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."MENSAJE_DESTINATARIO" (
		"ID_MENSAJE" BIGINT NOT NULL,
		"ID_PERSONA" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."MONEDA" (
		"ID_MONEDA" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"NOMBRE" VARCHAR(20) NOT NULL,
		"CODIGO" VARCHAR(10) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."MONEDA_COLEGIO" (
		"ID_COLEGIO" BIGINT NOT NULL,
		"ID_MONEDA" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."PERIODO_ACADEMICO" (
		"ID_PERIODO_ACADEMICO" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_COLEGIO" BIGINT NOT NULL,
		"ID_PARENT" BIGINT,
		"EN_CURSO" CHAR(1) NOT NULL,
		"ETIQUETA" VARCHAR(40) NOT NULL,
		"FECHA_INICIO" DATE NOT NULL,
		"FECHA_FIN" DATE NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."PERIODO_ACADEMICO_SECCION" (
		"ID_PERIODO_ACADEMICO_SECCION" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_SECCION" BIGINT NOT NULL,
		"ID_PERIODO_ACADEMICO" BIGINT NOT NULL,
		"ID_DOCENTE_TUTOR" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO" (
		"ID_PERIODO_ACADEMICO_SECCION_CURSO" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_PERIODO_ACADEMICO_SECCION" BIGINT NOT NULL,
		"ID_CURSO" INTEGER NOT NULL,
		"ID_DOCENTE" BIGINT NOT NULL,
		"FORMULA_NOTA_FINAL" VARCHAR(50),
		"ID_SECCION" BIGINT NOT NULL DEFAULT 1
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO_NOTA" (
		"ID_PERSONA" BIGINT NOT NULL,
		"ID_PERIODO_ACADEMICO_SECCION_CURSO" BIGINT NOT NULL,
		"NOTA_FINAL_CURSO" DECIMAL(2 , 2) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."PERMISO" (
		"ID_PERMISO" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_PERSONA" BIGINT NOT NULL,
		"FECHA_PERMISO" DATE NOT NULL,
		"PERSONA_ID_REGISTRO" BIGINT NOT NULL,
		"FECHA_REGISTRO" DATE NOT NULL,
		"COMENTARIOS" VARCHAR(400) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."PERSONA" (
		"ID_PERSONA" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"PRIMER_NOMBRE" VARCHAR(32600) NOT NULL,
		"FECHA_NACIMIENTO" DATE NOT NULL,
		"SEGUNDO_NOMBRE" VARCHAR(32600),
		"APELLIDO_PATERNO" VARCHAR(32600) NOT NULL,
		"APELLIDO_MATERNO" VARCHAR(32600) NOT NULL,
		"CODIGO" VARCHAR(10) NOT NULL,
		"USUARIO" VARCHAR(30),
		"PASSWORD" VARCHAR(20) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."PERSONA_MEDIO_CONTACTO" (
		"ID_PERSONA" BIGINT NOT NULL,
		"ID_MEDIO_CONTACTO" INTEGER NOT NULL,
		"REFERENCIA" VARCHAR(32600) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."RECIBO_PENSION" (
		"ID_RECIBO_PENSION" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_ALUMNO" BIGINT NOT NULL,
		"ID_PERIODO_ACADEMICO" BIGINT NOT NULL,
		"FECHA_EMISION" DATE NOT NULL,
		"ID_MONEDA" BIGINT NOT NULL,
		"FECHA_MAXIMA_PAGO" DATE NOT NULL,
		"FECHA_PAGO" DATE,
		"ID_COLEGIO" BIGINT NOT NULL,
		"MORA" DECIMAL(4 , 2) NOT NULL,
		"MONTO" DECIMAL(10 , 2) NOT NULL,
		"ID_BANCO" SMALLINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."RECIBO_PENSION_DETALLE" (
		"ID_RECIBO_PENSION" BIGINT NOT NULL,
		"ID_CONCEPTO" INTEGER NOT NULL,
		"CANTIDAD" SMALLINT NOT NULL,
		"PRECIO" DECIMAL(10 , 2) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."REPOSITORIO_ARCHIVOS" (
		"ID_REPOSITORIO" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20),
		"ID_COLEGIO" BIGINT NOT NULL,
		"URL" VARCHAR(60) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."RESUMEN_ALUMNO" (
		"ID_PERIODO_ACADEMICO" BIGINT NOT NULL,
		"ID_PERSONA" BIGINT NOT NULL,
		"ID_GRADO" INTEGER NOT NULL,
		"ID_SECCION" BIGINT NOT NULL,
		"ID_COLEGIO" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."SECCION" (
		"ID_SECCION" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"CORRELATIVO" INTEGER NOT NULL,
		"ETIQUETA" VARCHAR(6) NOT NULL,
		"ID_COLEGIO" BIGINT NOT NULL,
		"ID_GRADO" INTEGER NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO" (
		"ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20),
		"ID_CURSO" INTEGER NOT NULL,
		"FORMULA_NOTA_SUB_PERIODO" VARCHAR(50) NOT NULL,
		"ID_SUB_PERIODO_ACADEMICO" BIGINT NOT NULL,
		"ID_PERIODO_ACADEMICO_SECCION_CURSO" BIGINT NOT NULL,
		"ID_SECCION" BIGINT NOT NULL DEFAULT 1
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."TIPO_APODERADO" (
		"ID_TIPO_APODERADO" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 NO CYCLE CACHE 20),
		"NOMBRE" VARCHAR(20) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."TIPO_ASIGNACION" (
		"ID_TIPO_ASIGNACION" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 NO CYCLE CACHE 20),
		"NOMBRE" VARCHAR(30) NOT NULL,
		"ID_COLEGIO" BIGINT NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE "USER06279"."TIPO_EVALUACION" (
		"ID_TIPO_EVALUACION" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20),
		"ID_COLEGIO" BIGINT NOT NULL,
		"NOMBRE" VARCHAR(32600) NOT NULL,
		"DESCRIPCION" VARCHAR(32600) NOT NULL,
		"CODIGO" VARCHAR(3) NOT NULL
	)
	DATA CAPTURE NONE;

ALTER TABLE "USER06279"."ALUMNO" ADD CONSTRAINT "ALUMNO_PK" PRIMARY KEY
	("ID_PERSONA");

ALTER TABLE "USER06279"."ALUMNO_APODERADO" ADD CONSTRAINT "ALUMNO_APODERADO_PK" PRIMARY KEY
	("ID_PERSONA_APODERADO",
	 "ID_PERSONA_ALUMNO");

ALTER TABLE "USER06279"."APODERADO" ADD CONSTRAINT "APODERADO_PK" PRIMARY KEY
	("ID_PERSONA");

ALTER TABLE "USER06279"."ASIGNACION" ADD CONSTRAINT "ASIGNACION_PK" PRIMARY KEY
	("ID_ASIGNACION");

ALTER TABLE "USER06279"."ASIGNACION_ALUMNO" ADD CONSTRAINT "ASIGNACION_ALUMNO_PK" PRIMARY KEY
	("ID_ASIGNACION_ALUMNO");

ALTER TABLE "USER06279"."ASISTENCIA" ADD CONSTRAINT "ASISTENCIA_PK" PRIMARY KEY
	("ID_ASISTENCIA");

ALTER TABLE "USER06279"."AVISO" ADD CONSTRAINT "AVISO_PK" PRIMARY KEY
	("ID_AVISO");

ALTER TABLE "USER06279"."BANCO" ADD CONSTRAINT "BANCO_PK" PRIMARY KEY
	("ID_BANCO");

ALTER TABLE "USER06279"."COLEGIO" ADD CONSTRAINT "COLEGIO_PK" PRIMARY KEY
	("ID_COLEGIO");

ALTER TABLE "USER06279"."COLEGIO_MEDIO_CONTACTO" ADD CONSTRAINT "COLEGIO_MEDIO_CONTACTO_PK" PRIMARY KEY
	("ID_COLEGIO",
	 "ID_MEDIO_CONTACTO");

ALTER TABLE "USER06279"."CONCEPTO" ADD CONSTRAINT "CONCEPTO_PK" PRIMARY KEY
	("ID_CONCEPTO");

ALTER TABLE "USER06279"."CUENTA_BANCO" ADD CONSTRAINT "CUENTA_BANCO_PK" PRIMARY KEY
	("ID_BANCO",
	 "ID_COLEGIO");

ALTER TABLE "USER06279"."CURSO" ADD CONSTRAINT "CURSO_PK" PRIMARY KEY
	("ID_CURSO");

ALTER TABLE "USER06279"."CURSO_GRADO" ADD CONSTRAINT "CURSO_GRADO_PK" PRIMARY KEY
	("ID_CURSO",
	 "ID_GRADO");

ALTER TABLE "USER06279"."DOCENTE" ADD CONSTRAINT "DOCENTE_PK" PRIMARY KEY
	("ID_PERSONA");

ALTER TABLE "USER06279"."EVALUACION" ADD CONSTRAINT "EVALUACION_PK" PRIMARY KEY
	("ID_EVALUACION");

ALTER TABLE "USER06279"."EVALUACION_ALUMNO" ADD CONSTRAINT "EVALUACION_ALUMNO_PK" PRIMARY KEY
	("ID_EVALUACION_ALUMNO");

ALTER TABLE "USER06279"."FOTO_PERSONA" ADD CONSTRAINT "FOTO_PERSONA_PK" PRIMARY KEY
	("ID_FOTO");

ALTER TABLE "USER06279"."GRADO" ADD CONSTRAINT "GRADO_PK" PRIMARY KEY
	("ID_GRADO");

ALTER TABLE "USER06279"."JUSTIFICACION" ADD CONSTRAINT "JUSTIFICACION_PK" PRIMARY KEY
	("ID_JUSTIFICACION");

ALTER TABLE "USER06279"."LIBRETA_NOTAS" ADD CONSTRAINT "LIBRETA_NOTAS_PK" PRIMARY KEY
	("ID_LIBRETA_NOTAS");

ALTER TABLE "USER06279"."LIBRETA_NOTAS_FINALES_CURSO" ADD CONSTRAINT "LIBRETA_NOTAS_FINALES_CURSO_PK" PRIMARY KEY
	("ID");

ALTER TABLE "USER06279"."LIBRETA_NOTAS_SUBPERIODO" ADD CONSTRAINT "LIBRETA_NOTAS_SUBPERIODO_PK" PRIMARY KEY
	("ID_LIBRETA_NOTAS_SUBPERIODO");

ALTER TABLE "USER06279"."MATERIALES" ADD CONSTRAINT "MATERIALES_PK" PRIMARY KEY
	("ID_MATERIAL");

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_PERIODO" ADD CONSTRAINT "MATERIAL_SECCION_CURSO_PERIODO_PK" PRIMARY KEY
	("ID_PERIODO_ACADEMICO_SECCION_CURSO",
	 "ID_MATERIAL");

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_SUB_PERIODO" ADD CONSTRAINT "MATERIAL_SECCION_CURSO_SUB_PERIODO_PK" PRIMARY KEY
	("ID_MATERIAL",
	 "ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."MATRICULA_ALUMNO" ADD CONSTRAINT "MATRICULA_ALUMNO_PK" PRIMARY KEY
	("ID_MATRICULA");

ALTER TABLE "USER06279"."MEDIO_CONTACTO" ADD CONSTRAINT "MEDIO_CONTACTO_PK" PRIMARY KEY
	("ID_MEDIO_CONTACTO");

ALTER TABLE "USER06279"."MENSAJE" ADD CONSTRAINT "MENSAJE_PK" PRIMARY KEY
	("ID_MENSAJE");

ALTER TABLE "USER06279"."MONEDA" ADD CONSTRAINT "MONEDA_PK" PRIMARY KEY
	("ID_MONEDA");

ALTER TABLE "USER06279"."MONEDA_COLEGIO" ADD CONSTRAINT "MONEDA_COLEGIO_PK" PRIMARY KEY
	("ID_COLEGIO",
	 "ID_MONEDA");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO" ADD CONSTRAINT "PERIODO_ACADEMICO_PK" PRIMARY KEY
	("ID_PERIODO_ACADEMICO");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION" ADD CONSTRAINT "PERIODO_ACADEMICO_SECCION_PK" PRIMARY KEY
	("ID_PERIODO_ACADEMICO_SECCION");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO" ADD CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_PK" PRIMARY KEY
	("ID_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO_NOTA" ADD CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_NOTA_PK" PRIMARY KEY
	("ID_PERSONA");

ALTER TABLE "USER06279"."PERMISO" ADD CONSTRAINT "PERMISO_PK" PRIMARY KEY
	("ID_PERMISO");

ALTER TABLE "USER06279"."PERSONA" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY
	("ID_PERSONA");

ALTER TABLE "USER06279"."PERSONA_MEDIO_CONTACTO" ADD CONSTRAINT "PERSONA_MEDIO_CONTACTO_PK" PRIMARY KEY
	("ID_PERSONA",
	 "ID_MEDIO_CONTACTO");

ALTER TABLE "USER06279"."RECIBO_PENSION" ADD CONSTRAINT "RECIBO_PENSION_PK" PRIMARY KEY
	("ID_RECIBO_PENSION");

ALTER TABLE "USER06279"."RECIBO_PENSION_DETALLE" ADD CONSTRAINT "RECIBO_PENSION_DETALLE_PK" PRIMARY KEY
	("ID_RECIBO_PENSION");

ALTER TABLE "USER06279"."REPOSITORIO_ARCHIVOS" ADD CONSTRAINT "REPOSITORIO_ARCHIVOS_PK" PRIMARY KEY
	("ID_REPOSITORIO");

ALTER TABLE "USER06279"."RESUMEN_ALUMNO" ADD CONSTRAINT "RESUMEN_ALUMNO_PK" PRIMARY KEY
	("ID_PERIODO_ACADEMICO",
	 "ID_PERSONA");

ALTER TABLE "USER06279"."SECCION" ADD CONSTRAINT "SECCION_PK" PRIMARY KEY
	("ID_SECCION");

ALTER TABLE "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO" ADD CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_PK" PRIMARY KEY
	("ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."TIPO_APODERADO" ADD CONSTRAINT "TIPO_APODERADO_PK" PRIMARY KEY
	("ID_TIPO_APODERADO");

ALTER TABLE "USER06279"."TIPO_ASIGNACION" ADD CONSTRAINT "TIPO_ASIGNACION_PK" PRIMARY KEY
	("ID_TIPO_ASIGNACION");

ALTER TABLE "USER06279"."TIPO_EVALUACION" ADD CONSTRAINT "TIPO_EVALUACION_PK" PRIMARY KEY
	("ID_TIPO_EVALUACION");

ALTER TABLE "USER06279"."ALUMNO" ADD CONSTRAINT "COLEGIO_ALUMNO_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."ALUMNO" ADD CONSTRAINT "PERSONA_ALUMNO_FK" FOREIGN KEY
	("ID_PERSONA")
	REFERENCES "USER06279"."PERSONA"
	("ID_PERSONA");

ALTER TABLE "USER06279"."ALUMNO_APODERADO" ADD CONSTRAINT "ALUMNO_ALUMNO_APODERADO_FK" FOREIGN KEY
	("ID_PERSONA_ALUMNO")
	REFERENCES "USER06279"."ALUMNO"
	("ID_PERSONA");

ALTER TABLE "USER06279"."ALUMNO_APODERADO" ADD CONSTRAINT "APODERADO_ALUMNO_APODERADO_FK" FOREIGN KEY
	("ID_PERSONA_APODERADO")
	REFERENCES "USER06279"."APODERADO"
	("ID_PERSONA");

ALTER TABLE "USER06279"."APODERADO" ADD CONSTRAINT "PERSONA_APODERADO_FK" FOREIGN KEY
	("ID_PERSONA")
	REFERENCES "USER06279"."PERSONA"
	("ID_PERSONA");

ALTER TABLE "USER06279"."APODERADO" ADD CONSTRAINT "TIPO_APODERADO_APODERADO_FK" FOREIGN KEY
	("ID_TIPO_APODERADO")
	REFERENCES "USER06279"."TIPO_APODERADO"
	("ID_TIPO_APODERADO");

ALTER TABLE "USER06279"."ASIGNACION" ADD CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_ASIGNACIONES_FK" FOREIGN KEY
	("ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO")
	REFERENCES "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO"
	("ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."ASIGNACION" ADD CONSTRAINT "TIPO_ASIGNACION_ASIGNACIONES_FK" FOREIGN KEY
	("ID_TIPO_ASIGNACION")
	REFERENCES "USER06279"."TIPO_ASIGNACION"
	("ID_TIPO_ASIGNACION");

ALTER TABLE "USER06279"."ASIGNACION_ALUMNO" ADD CONSTRAINT "ALUMNO_ASIGNACION_ALUMNO_FK" FOREIGN KEY
	("ID_ALUMNO")
	REFERENCES "USER06279"."ALUMNO"
	("ID_PERSONA");

ALTER TABLE "USER06279"."ASIGNACION_ALUMNO" ADD CONSTRAINT "ASIGNACIONES_ASIGNACION_ALUMNO_FK" FOREIGN KEY
	("ID_ASIGNACION")
	REFERENCES "USER06279"."ASIGNACION"
	("ID_ASIGNACION");

ALTER TABLE "USER06279"."ASISTENCIA" ADD CONSTRAINT "ALUMNO_ASISTENCIA_FK" FOREIGN KEY
	("ID_ALUMNO")
	REFERENCES "USER06279"."ALUMNO"
	("ID_PERSONA");

ALTER TABLE "USER06279"."ASISTENCIA" ADD CONSTRAINT "CURSO_ASISTENCIA_FK" FOREIGN KEY
	("ID_CURSO")
	REFERENCES "USER06279"."CURSO"
	("ID_CURSO");

ALTER TABLE "USER06279"."ASISTENCIA" ADD CONSTRAINT "JUSTIFICACION_ASISTENCIA_FK" FOREIGN KEY
	("ID_JUSTIFICACION")
	REFERENCES "USER06279"."JUSTIFICACION"
	("ID_JUSTIFICACION");

ALTER TABLE "USER06279"."ASISTENCIA" ADD CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_ASISTENCIA_FK" FOREIGN KEY
	("ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO")
	REFERENCES "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO"
	("ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."AVISO" ADD CONSTRAINT "COLEGIO_ACTIVIDAD_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."AVISO_SECCION" ADD CONSTRAINT "ACTIVIDAD_ACTIVIDAD_SECCION_FK" FOREIGN KEY
	("ID_AVISO")
	REFERENCES "USER06279"."AVISO"
	("ID_AVISO");

ALTER TABLE "USER06279"."AVISO_SECCION" ADD CONSTRAINT "SECCION_ACTIVIDAD_SECCION_FK" FOREIGN KEY
	("ID_SECCION")
	REFERENCES "USER06279"."SECCION"
	("ID_SECCION");

ALTER TABLE "USER06279"."COLEGIO_MEDIO_CONTACTO" ADD CONSTRAINT "COLEGIO_COLEGIO_MEDIO_CONTACTO_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."COLEGIO_MEDIO_CONTACTO" ADD CONSTRAINT "MEDIO_CONTACTO_COLEGIO_MEDIO_CONTACTO_FK" FOREIGN KEY
	("ID_MEDIO_CONTACTO")
	REFERENCES "USER06279"."MEDIO_CONTACTO"
	("ID_MEDIO_CONTACTO");

ALTER TABLE "USER06279"."CONCEPTO" ADD CONSTRAINT "COLEGIO_CONCEPTO_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."CUENTA_BANCO" ADD CONSTRAINT "BANCO_CUENTA_BANCO_FK" FOREIGN KEY
	("ID_BANCO")
	REFERENCES "USER06279"."BANCO"
	("ID_BANCO");

ALTER TABLE "USER06279"."CUENTA_BANCO" ADD CONSTRAINT "COLEGIO_BANCO_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."CURSO" ADD CONSTRAINT "COLEGIO_CURSO_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."CURSO_GRADO" ADD CONSTRAINT "CURSO_CURSO_GRADO_FK" FOREIGN KEY
	("ID_CURSO")
	REFERENCES "USER06279"."CURSO"
	("ID_CURSO");

ALTER TABLE "USER06279"."CURSO_GRADO" ADD CONSTRAINT "GRADO_CURSO_GRADO_FK" FOREIGN KEY
	("ID_GRADO")
	REFERENCES "USER06279"."GRADO"
	("ID_GRADO");

ALTER TABLE "USER06279"."DOCENTE" ADD CONSTRAINT "COLEGIO_DOCENTE_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."DOCENTE" ADD CONSTRAINT "PERSONA_DOCENTE_FK" FOREIGN KEY
	("ID_PERSONA")
	REFERENCES "USER06279"."PERSONA"
	("ID_PERSONA");

ALTER TABLE "USER06279"."EVALUACION" ADD CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_EVALUACION_FK" FOREIGN KEY
	("ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO")
	REFERENCES "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO"
	("ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."EVALUACION" ADD CONSTRAINT "TIPO_EVALUACION_EVALUACION_FK" FOREIGN KEY
	("ID_TIPO_EVALUACION")
	REFERENCES "USER06279"."TIPO_EVALUACION"
	("ID_TIPO_EVALUACION");

ALTER TABLE "USER06279"."EVALUACION_ALUMNO" ADD CONSTRAINT "ALUMNO_EVALUACION_ALUMNO_FK" FOREIGN KEY
	("ID_ALUMNO")
	REFERENCES "USER06279"."ALUMNO"
	("ID_PERSONA");

ALTER TABLE "USER06279"."EVALUACION_ALUMNO" ADD CONSTRAINT "EVALUACION_EVALUACION_ALUMNO_FK" FOREIGN KEY
	("ID_EVALUACION")
	REFERENCES "USER06279"."EVALUACION"
	("ID_EVALUACION");

ALTER TABLE "USER06279"."FOTO_PERSONA" ADD CONSTRAINT "PERSONA_FOTO_FK" FOREIGN KEY
	("ID_PERSONA")
	REFERENCES "USER06279"."PERSONA"
	("ID_PERSONA");

ALTER TABLE "USER06279"."FOTO_PERSONA" ADD CONSTRAINT "REPOSITORIO_ARCHIVOS_FOTO_PERSONA_FK" FOREIGN KEY
	("ID_REPOSITORIO")
	REFERENCES "USER06279"."REPOSITORIO_ARCHIVOS"
	("ID_REPOSITORIO");

ALTER TABLE "USER06279"."GRADO" ADD CONSTRAINT "COLEGIO_GRADO_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."LIBRETA_NOTAS" ADD CONSTRAINT "ALUMNO_LIBRETA_NOTAS_FK" FOREIGN KEY
	("ID_ALUMNO")
	REFERENCES "USER06279"."ALUMNO"
	("ID_PERSONA");

ALTER TABLE "USER06279"."LIBRETA_NOTAS" ADD CONSTRAINT "PERIODO_ACADEMICO_SECCION_LIBRETA_NOTAS_FK" FOREIGN KEY
	("ID_PERIODO_ACADEMICO_SECCION")
	REFERENCES "USER06279"."PERIODO_ACADEMICO_SECCION"
	("ID_PERIODO_ACADEMICO_SECCION");

ALTER TABLE "USER06279"."LIBRETA_NOTAS" ADD CONSTRAINT "SECCION_LIBRETA_NOTAS_FK" FOREIGN KEY
	("ID_SECCION")
	REFERENCES "USER06279"."SECCION"
	("ID_SECCION");

ALTER TABLE "USER06279"."LIBRETA_NOTAS_FINALES_CURSO" ADD CONSTRAINT "CURSO_LIBRETA_NOTAS_FINALES_CURSO_FK" FOREIGN KEY
	("ID_CURSO")
	REFERENCES "USER06279"."CURSO"
	("ID_CURSO");

ALTER TABLE "USER06279"."LIBRETA_NOTAS_FINALES_CURSO" ADD CONSTRAINT "LIBRETA_NOTAS_LIBRETA_NOTAS_FINALES_FK" FOREIGN KEY
	("ID_LIBRETA_NOTAS")
	REFERENCES "USER06279"."LIBRETA_NOTAS"
	("ID_LIBRETA_NOTAS");

ALTER TABLE "USER06279"."LIBRETA_NOTAS_FINALES_CURSO" ADD CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_LIBRETA_NOTAS_FINALES_CURSO_FK" FOREIGN KEY
	("ID_PERIODO_ACADEMICO_SECCION_CURSO")
	REFERENCES "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO"
	("ID_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."LIBRETA_NOTAS_SUBPERIODO" ADD CONSTRAINT "CURSO_LIBRETA_NOTAS_SUBPERIODO_FK" FOREIGN KEY
	("ID_CURSO")
	REFERENCES "USER06279"."CURSO"
	("ID_CURSO");

ALTER TABLE "USER06279"."LIBRETA_NOTAS_SUBPERIODO" ADD CONSTRAINT "LIBRETA_NOTAS_LIBRETA_NOTAS_SUBPERIODO_FK" FOREIGN KEY
	("ID_LIBRETA_NOTAS")
	REFERENCES "USER06279"."LIBRETA_NOTAS"
	("ID_LIBRETA_NOTAS");

ALTER TABLE "USER06279"."LIBRETA_NOTAS_SUBPERIODO" ADD CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_LIBRETA_NOTAS_SUBPERIODO_FK" FOREIGN KEY
	("ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO")
	REFERENCES "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO"
	("ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."MATERIALES" ADD CONSTRAINT "REPOSITORIO_ARCHIVOS_MATERIALES_FK" FOREIGN KEY
	("ID_REPOSITORIO")
	REFERENCES "USER06279"."REPOSITORIO_ARCHIVOS"
	("ID_REPOSITORIO");

ALTER TABLE "USER06279"."MATERIAL_ASIGNACION" ADD CONSTRAINT "ASIGNACIONES_MATERIAL_EVALUACION_FK" FOREIGN KEY
	("ID_ASIGNACION")
	REFERENCES "USER06279"."ASIGNACION"
	("ID_ASIGNACION");

ALTER TABLE "USER06279"."MATERIAL_ASIGNACION" ADD CONSTRAINT "MATERIALES_MATERIAL_EVALUACION_FK1" FOREIGN KEY
	("ID_MATERIAL")
	REFERENCES "USER06279"."MATERIALES"
	("ID_MATERIAL");

ALTER TABLE "USER06279"."MATERIAL_EVALUACION" ADD CONSTRAINT "EVALUACION_MATERIAL_EVALUACION_FK" FOREIGN KEY
	("ID_EVALUACION")
	REFERENCES "USER06279"."EVALUACION"
	("ID_EVALUACION");

ALTER TABLE "USER06279"."MATERIAL_EVALUACION" ADD CONSTRAINT "MATERIALES_MATERIAL_EVALUACION_FK" FOREIGN KEY
	("ID_MATERIAL")
	REFERENCES "USER06279"."MATERIALES"
	("ID_MATERIAL");

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_PERIODO" ADD CONSTRAINT "MATERIALES_MATERIAL_SECCION_CURSO_PERIODO_FK" FOREIGN KEY
	("ID_MATERIAL")
	REFERENCES "USER06279"."MATERIALES"
	("ID_MATERIAL");

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_PERIODO" ADD CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_MATERIAL_SECCION_CURSO_PERIO950" FOREIGN KEY
	("ID_PERIODO_ACADEMICO_SECCION_CURSO")
	REFERENCES "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO"
	("ID_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_SUB_PERIODO" ADD CONSTRAINT "MATERIALES_MATERIAL_SECCION_CURSO_SUB_PERIODO_FK" FOREIGN KEY
	("ID_MATERIAL")
	REFERENCES "USER06279"."MATERIALES"
	("ID_MATERIAL");

ALTER TABLE "USER06279"."MATERIAL_SECCION_CURSO_SUB_PERIODO" ADD CONSTRAINT "SUB_PERIODO_ACADEMICO_SECCION_CURSO_MATERIAL_SECCION_CURSO_S478" FOREIGN KEY
	("ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO")
	REFERENCES "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO"
	("ID_SUB_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."MATRICULA_ALUMNO" ADD CONSTRAINT "ALUMNO_MATRICULA_ALUMNO_FK" FOREIGN KEY
	("ID_ALUMNO")
	REFERENCES "USER06279"."ALUMNO"
	("ID_PERSONA");

ALTER TABLE "USER06279"."MATRICULA_ALUMNO" ADD CONSTRAINT "PERIODO_ACADEMICO_SECCION_MATRICULA_ALUMNO_FK" FOREIGN KEY
	("ID_PERIODO_ACADEMICO_SECCION")
	REFERENCES "USER06279"."PERIODO_ACADEMICO_SECCION"
	("ID_PERIODO_ACADEMICO_SECCION");

ALTER TABLE "USER06279"."MENSAJE" ADD CONSTRAINT "MENSAJE_MENSAJE_FK" FOREIGN KEY
	("PARENT_ID_MENSAJE")
	REFERENCES "USER06279"."MENSAJE"
	("ID_MENSAJE");

ALTER TABLE "USER06279"."MENSAJE" ADD CONSTRAINT "PERSONA_MENSAJE_FK" FOREIGN KEY
	("ID_PERSONA_FROM")
	REFERENCES "USER06279"."PERSONA"
	("ID_PERSONA");

ALTER TABLE "USER06279"."MENSAJE_DESTINATARIO" ADD CONSTRAINT "MENSAJE_MENSAJE_DESTINATARIO_FK" FOREIGN KEY
	("ID_MENSAJE")
	REFERENCES "USER06279"."MENSAJE"
	("ID_MENSAJE");

ALTER TABLE "USER06279"."MENSAJE_DESTINATARIO" ADD CONSTRAINT "PERSONA_MENSAJE_DESTINATARIO_FK" FOREIGN KEY
	("ID_PERSONA")
	REFERENCES "USER06279"."PERSONA"
	("ID_PERSONA");

ALTER TABLE "USER06279"."MONEDA_COLEGIO" ADD CONSTRAINT "COLEGIO_MONEDA_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."MONEDA_COLEGIO" ADD CONSTRAINT "MONEDA_MONEDA_COLEGIO_FK" FOREIGN KEY
	("ID_MONEDA")
	REFERENCES "USER06279"."MONEDA"
	("ID_MONEDA");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO" ADD CONSTRAINT "COLEGIO_PERIODO_ACADEMICO_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO" ADD CONSTRAINT "PERIODO_ACADEMICO_PERIODO_ACADEMICO_FK" FOREIGN KEY
	("ID_PARENT")
	REFERENCES "USER06279"."PERIODO_ACADEMICO"
	("ID_PERIODO_ACADEMICO");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION" ADD CONSTRAINT "SECCION_PERIODO_ACADEMICO_SECCION_FK" FOREIGN KEY
	("ID_SECCION")
	REFERENCES "USER06279"."SECCION"
	("ID_SECCION");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO" ADD CONSTRAINT "CURSO_SECCION_CURSO_FK" FOREIGN KEY
	("ID_CURSO")
	REFERENCES "USER06279"."CURSO"
	("ID_CURSO");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO" ADD CONSTRAINT "DOCENTE_PERIODO_ACADEMICO_SECCION_CURSO_FK" FOREIGN KEY
	("ID_DOCENTE")
	REFERENCES "USER06279"."DOCENTE"
	("ID_PERSONA");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO" ADD CONSTRAINT "PERIODO_ACADEMICO_SECCION_PERIODO_ACADEMICO_SECCION_CURSO_FK" FOREIGN KEY
	("ID_PERIODO_ACADEMICO_SECCION")
	REFERENCES "USER06279"."PERIODO_ACADEMICO_SECCION"
	("ID_PERIODO_ACADEMICO_SECCION");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO" ADD CONSTRAINT "SECCION_PERIODO_ACADEMICO_SECCION_CURSO_FK" FOREIGN KEY
	("ID_SECCION")
	REFERENCES "USER06279"."SECCION"
	("ID_SECCION");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO_NOTA" ADD CONSTRAINT "ALUMNO_PERIODO_ACADEMICO_SECCION_CURSO_ALUMNO_FK" FOREIGN KEY
	("ID_PERSONA")
	REFERENCES "USER06279"."ALUMNO"
	("ID_PERSONA");

ALTER TABLE "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO_NOTA" ADD CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_PERIODO_ACADEMICO_SECCION_CU584" FOREIGN KEY
	("ID_PERIODO_ACADEMICO_SECCION_CURSO")
	REFERENCES "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO"
	("ID_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."PERMISO" ADD CONSTRAINT "PERSONA_PERMISO_FK" FOREIGN KEY
	("ID_PERSONA")
	REFERENCES "USER06279"."PERSONA"
	("ID_PERSONA");

ALTER TABLE "USER06279"."PERMISO" ADD CONSTRAINT "PERSONA_PERMISO_FK1" FOREIGN KEY
	("PERSONA_ID_REGISTRO")
	REFERENCES "USER06279"."PERSONA"
	("ID_PERSONA");

ALTER TABLE "USER06279"."PERSONA_MEDIO_CONTACTO" ADD CONSTRAINT "MEDIO_CONTACTO_PERSONA_MEDIO_CONTACTO_FK" FOREIGN KEY
	("ID_MEDIO_CONTACTO")
	REFERENCES "USER06279"."MEDIO_CONTACTO"
	("ID_MEDIO_CONTACTO");

ALTER TABLE "USER06279"."PERSONA_MEDIO_CONTACTO" ADD CONSTRAINT "PERSONA_PERSONA_MEDIO_CONTACTO_FK" FOREIGN KEY
	("ID_PERSONA")
	REFERENCES "USER06279"."PERSONA"
	("ID_PERSONA");

ALTER TABLE "USER06279"."RECIBO_PENSION" ADD CONSTRAINT "ALUMNO_RECIBO_PENSION_FK" FOREIGN KEY
	("ID_ALUMNO")
	REFERENCES "USER06279"."ALUMNO"
	("ID_PERSONA");

ALTER TABLE "USER06279"."RECIBO_PENSION" ADD CONSTRAINT "BANCO_RECIBO_PENSION_FK" FOREIGN KEY
	("ID_BANCO",
	 "ID_COLEGIO")
	REFERENCES "USER06279"."CUENTA_BANCO"
	("ID_BANCO",
	 "ID_COLEGIO");

ALTER TABLE "USER06279"."RECIBO_PENSION" ADD CONSTRAINT "MONEDA_RECIBO_PENSION_FK" FOREIGN KEY
	("ID_MONEDA")
	REFERENCES "USER06279"."MONEDA"
	("ID_MONEDA");

ALTER TABLE "USER06279"."RECIBO_PENSION_DETALLE" ADD CONSTRAINT "CONCEPTO_RECIBO_PENSION_DETALLE_FK" FOREIGN KEY
	("ID_CONCEPTO")
	REFERENCES "USER06279"."CONCEPTO"
	("ID_CONCEPTO");

ALTER TABLE "USER06279"."RECIBO_PENSION_DETALLE" ADD CONSTRAINT "RECIBO_PENSION_RECIBO_PENSION_DETALLE_FK" FOREIGN KEY
	("ID_RECIBO_PENSION")
	REFERENCES "USER06279"."RECIBO_PENSION"
	("ID_RECIBO_PENSION");

ALTER TABLE "USER06279"."REPOSITORIO_ARCHIVOS" ADD CONSTRAINT "COLEGIO_REPOSITORIO_ARCHIVOS_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."RESUMEN_ALUMNO" ADD CONSTRAINT "ALUMNO_RESUMEN_ALUMNO_FK" FOREIGN KEY
	("ID_PERSONA")
	REFERENCES "USER06279"."ALUMNO"
	("ID_PERSONA");

ALTER TABLE "USER06279"."RESUMEN_ALUMNO" ADD CONSTRAINT "COLEGIO_RESUMEN_ALUMNO_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."RESUMEN_ALUMNO" ADD CONSTRAINT "GRADO_RESUMEN_ALUMNO_FK" FOREIGN KEY
	("ID_GRADO")
	REFERENCES "USER06279"."GRADO"
	("ID_GRADO");

ALTER TABLE "USER06279"."RESUMEN_ALUMNO" ADD CONSTRAINT "SECCION_RESUMEN_ALUMNO_FK" FOREIGN KEY
	("ID_SECCION")
	REFERENCES "USER06279"."SECCION"
	("ID_SECCION");

ALTER TABLE "USER06279"."SECCION" ADD CONSTRAINT "COLEGIO_SECCION_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."SECCION" ADD CONSTRAINT "GRADO_SECCION_FK" FOREIGN KEY
	("ID_GRADO")
	REFERENCES "USER06279"."GRADO"
	("ID_GRADO");

ALTER TABLE "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO" ADD CONSTRAINT "CURSO_SUB_PERIODO_ACADEMICO_SECCION_CURSO_FK" FOREIGN KEY
	("ID_CURSO")
	REFERENCES "USER06279"."CURSO"
	("ID_CURSO");

ALTER TABLE "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO" ADD CONSTRAINT "PERIODO_ACADEMICO_SECCION_CURSO_SUB_PERIODO_ACADEMICO_SECCIO60" FOREIGN KEY
	("ID_PERIODO_ACADEMICO_SECCION_CURSO")
	REFERENCES "USER06279"."PERIODO_ACADEMICO_SECCION_CURSO"
	("ID_PERIODO_ACADEMICO_SECCION_CURSO");

ALTER TABLE "USER06279"."SUB_PERIODO_ACADEMICO_SECCION_CURSO" ADD CONSTRAINT "SECCION_SUB_PERIODO_ACADEMICO_SECCION_CURSO_FK" FOREIGN KEY
	("ID_SECCION")
	REFERENCES "USER06279"."SECCION"
	("ID_SECCION");

ALTER TABLE "USER06279"."TIPO_ASIGNACION" ADD CONSTRAINT "COLEGIO_TIPO_ASIGNACION_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

ALTER TABLE "USER06279"."TIPO_EVALUACION" ADD CONSTRAINT "COLEGIO_TIPO_EVALUACION_FK" FOREIGN KEY
	("ID_COLEGIO")
	REFERENCES "USER06279"."COLEGIO"
	("ID_COLEGIO");

GRANT ALTERIN ON SCHEMA "USER06279" TO USER "DB2INST1" WITH GRANT OPTION;

GRANT CREATEIN ON SCHEMA "USER06279" TO USER "DB2INST1" WITH GRANT OPTION;

GRANT DROPIN ON SCHEMA "USER06279" TO USER "DB2INST1" WITH GRANT OPTION;

