package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AvisoSeccionId generated by hbm2java
 */
@Embeddable
public class AvisoSeccionId  implements java.io.Serializable {


     private long idAviso;
     private long idSeccion;

    public AvisoSeccionId() {
    }

    public AvisoSeccionId(long idAviso, long idSeccion) {
       this.idAviso = idAviso;
       this.idSeccion = idSeccion;
    }
   


    @Column(name="id_aviso", nullable=false)
    public long getIdAviso() {
        return this.idAviso;
    }
    
    public void setIdAviso(long idAviso) {
        this.idAviso = idAviso;
    }


    @Column(name="id_seccion", nullable=false)
    public long getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(long idSeccion) {
        this.idSeccion = idSeccion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AvisoSeccionId) ) return false;
		 AvisoSeccionId castOther = ( AvisoSeccionId ) other; 
         
		 return (this.getIdAviso()==castOther.getIdAviso())
 && (this.getIdSeccion()==castOther.getIdSeccion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdAviso();
         result = 37 * result + (int) this.getIdSeccion();
         return result;
   }   


}


