package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name="banco"
)
public class Banco  implements java.io.Serializable {


     private short idBanco;
     private String nombre;
     private String abreviatura;
     private CuentaBanco cuentaBanco;

    public Banco() {
    }

	
    public Banco(short idBanco, String nombre, String abreviatura) {
        this.idBanco = idBanco;
        this.nombre = nombre;
        this.abreviatura = abreviatura;
    }
    public Banco(short idBanco, String nombre, String abreviatura, CuentaBanco cuentaBanco) {
       this.idBanco = idBanco;
       this.nombre = nombre;
       this.abreviatura = abreviatura;
       this.cuentaBanco = cuentaBanco;
    }
   
     @Id 

    
    @Column(name="id_banco", unique=true, nullable=false)
    public short getIdBanco() {
        return this.idBanco;
    }
    
    public void setIdBanco(short idBanco) {
        this.idBanco = idBanco;
    }

    
    @Column(name="nombre", nullable=false, length=40)
    @NotNull
    @Length(max=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="abreviatura", nullable=false, length=10)
    @NotNull
    @Length(max=10)
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="banco")
    public CuentaBanco getCuentaBanco() {
        return this.cuentaBanco;
    }
    
    public void setCuentaBanco(CuentaBanco cuentaBanco) {
        this.cuentaBanco = cuentaBanco;
    }




}


