package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.Name;

/**
 * ColegioMedioContacto generated by hbm2java
 */
@Entity
@Table(name="colegio_medio_contacto")
@Name("colegioMedioContacto")
public class ColegioMedioContacto  implements java.io.Serializable {


     private ColegioMedioContactoId id;
     private Colegio colegio;
     private MedioContacto medioContacto;

    public ColegioMedioContacto() {
    }
    

    public ColegioMedioContacto(ColegioMedioContactoId id, Colegio colegio, MedioContacto medioContacto) {
       this.id = id;
       this.colegio = colegio;
       this.medioContacto = medioContacto;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idColegio", column=@Column(name="id_colegio", nullable=false) ), 
        @AttributeOverride(name="idMedioContacto", column=@Column(name="id_medio_contacto", nullable=false) ), 
        @AttributeOverride(name="referencia", column=@Column(name="referencia", nullable=false) ) } )
    @NotNull
    public ColegioMedioContactoId getId() {
        return this.id;
    }
    
    public void setId(ColegioMedioContactoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_colegio", nullable=false, insertable=false, updatable=false)
    @NotNull
    public Colegio getColegio() {
        return this.colegio;
    }
    
    public void setColegio(Colegio colegio) {
        this.colegio = colegio;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_medio_contacto", nullable=false, insertable=false, updatable=false)
    @NotNull
    public MedioContacto getMedioContacto() {
        return this.medioContacto;
    }
    
    public void setMedioContacto(MedioContacto medioContacto) {
        this.medioContacto = medioContacto;
    }




}


