package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.NotNull;

/**
 * ColegioMedioContactoId generated by hbm2java
 */
@Embeddable
public class ColegioMedioContactoId  implements java.io.Serializable {


     private long idColegio;
     private int idMedioContacto;
     private String referencia;

    public ColegioMedioContactoId() {
    }

    public ColegioMedioContactoId(long idColegio, int idMedioContacto, String referencia) {
       this.idColegio = idColegio;
       this.idMedioContacto = idMedioContacto;
       this.referencia = referencia;
    }
   


    @Column(name="id_colegio", nullable=false)
    public long getIdColegio() {
        return this.idColegio;
    }
    
    public void setIdColegio(long idColegio) {
        this.idColegio = idColegio;
    }


    @Column(name="id_medio_contacto", nullable=false)
    public int getIdMedioContacto() {
        return this.idMedioContacto;
    }
    
    public void setIdMedioContacto(int idMedioContacto) {
        this.idMedioContacto = idMedioContacto;
    }


    @Column(name="referencia", nullable=false)
    @NotNull
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ColegioMedioContactoId) ) return false;
		 ColegioMedioContactoId castOther = ( ColegioMedioContactoId ) other; 
         
		 return (this.getIdColegio()==castOther.getIdColegio())
 && (this.getIdMedioContacto()==castOther.getIdMedioContacto())
 && ( (this.getReferencia()==castOther.getReferencia()) || ( this.getReferencia()!=null && castOther.getReferencia()!=null && this.getReferencia().equals(castOther.getReferencia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdColegio();
         result = 37 * result + this.getIdMedioContacto();
         result = 37 * result + ( getReferencia() == null ? 0 : this.getReferencia().hashCode() );
         return result;
   }   


}


