package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Concepto generated by hbm2java
 */
@Entity
@Table(name="concepto"
)
public class Concepto  implements java.io.Serializable {


     private int idConcepto;
     private Colegio colegio;
     private String nombre;
     private Set<ReciboPensionDetalle> reciboPensionDetalles = new HashSet<ReciboPensionDetalle>(0);

    public Concepto() {
    }

	
    public Concepto(int idConcepto, Colegio colegio, String nombre) {
        this.idConcepto = idConcepto;
        this.colegio = colegio;
        this.nombre = nombre;
    }
    public Concepto(int idConcepto, Colegio colegio, String nombre, Set<ReciboPensionDetalle> reciboPensionDetalles) {
       this.idConcepto = idConcepto;
       this.colegio = colegio;
       this.nombre = nombre;
       this.reciboPensionDetalles = reciboPensionDetalles;
    }
   
     @Id 

    
    @Column(name="id_concepto", unique=true, nullable=false)
    public int getIdConcepto() {
        return this.idConcepto;
    }
    
    public void setIdConcepto(int idConcepto) {
        this.idConcepto = idConcepto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_colegio", nullable=false)
    @NotNull
    public Colegio getColegio() {
        return this.colegio;
    }
    
    public void setColegio(Colegio colegio) {
        this.colegio = colegio;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    @NotNull
    @Length(max=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="concepto")
    public Set<ReciboPensionDetalle> getReciboPensionDetalles() {
        return this.reciboPensionDetalles;
    }
    
    public void setReciboPensionDetalles(Set<ReciboPensionDetalle> reciboPensionDetalles) {
        this.reciboPensionDetalles = reciboPensionDetalles;
    }




}


