package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CuentaBanco generated by hbm2java
 */
@Entity
@Table(name="cuenta_banco"
)
public class CuentaBanco  implements java.io.Serializable {


     private short idBanco;
     private Colegio colegio;
     private Banco banco;
     private String numero;
     private Set<ReciboPension> reciboPensions = new HashSet<ReciboPension>(0);

    public CuentaBanco() {
    }

	
    public CuentaBanco(Colegio colegio, Banco banco, String numero) {
        this.colegio = colegio;
        this.banco = banco;
        this.numero = numero;
    }
    public CuentaBanco(Colegio colegio, Banco banco, String numero, Set<ReciboPension> reciboPensions) {
       this.colegio = colegio;
       this.banco = banco;
       this.numero = numero;
       this.reciboPensions = reciboPensions;
    }
   
     //@GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="banco"))
    @Id 
    //@GeneratedValue(generator="generator")
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id_banco", unique=true, nullable=false)
    public short getIdBanco() {
        return this.idBanco;
    }
    
    public void setIdBanco(short idBanco) {
        this.idBanco = idBanco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_colegio", nullable=false)
    @NotNull
    public Colegio getColegio() {
        return this.colegio;
    }
    
    public void setColegio(Colegio colegio) {
        this.colegio = colegio;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    @NotNull
    public Banco getBanco() {
        return this.banco;
    }
    
    public void setBanco(Banco banco) {
        this.banco = banco;
    }

    
    @Column(name="numero", nullable=false, length=25)
    @NotNull
    @Length(max=25)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cuentaBanco")
    public Set<ReciboPension> getReciboPensions() {
        return this.reciboPensions;
    }
    
    public void setReciboPensions(Set<ReciboPension> reciboPensions) {
        this.reciboPensions = reciboPensions;
    }




}


