package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * EvaluacionAlumno generated by hbm2java
 */
@Entity
@Table(name="evaluacion_alumno"
)
public class EvaluacionAlumno  implements java.io.Serializable {


     private long idEvaluacionAlumno;
     private Evaluacion evaluacion;
     private Alumno alumno;
     private PeriodoAcademico periodoAcademico;
     private Date fechaIngreso;
     private BigDecimal nota;

    public EvaluacionAlumno() {
    }

    public EvaluacionAlumno(long idEvaluacionAlumno, Evaluacion evaluacion, Alumno alumno, PeriodoAcademico periodoAcademico, Date fechaIngreso, BigDecimal nota) {
       this.idEvaluacionAlumno = idEvaluacionAlumno;
       this.evaluacion = evaluacion;
       this.alumno = alumno;
       this.periodoAcademico = periodoAcademico;
       this.fechaIngreso = fechaIngreso;
       this.nota = nota;
    }
   
     @Id 

    
    @Column(name="id_evaluacion_alumno", unique=true, nullable=false)
    public long getIdEvaluacionAlumno() {
        return this.idEvaluacionAlumno;
    }
    
    public void setIdEvaluacionAlumno(long idEvaluacionAlumno) {
        this.idEvaluacionAlumno = idEvaluacionAlumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_evaluacion", nullable=false)
    @NotNull
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_alumno", nullable=false)
    @NotNull
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_periodo", nullable=false)
    @NotNull
    public PeriodoAcademico getPeriodoAcademico() {
        return this.periodoAcademico;
    }
    
    public void setPeriodoAcademico(PeriodoAcademico periodoAcademico) {
        this.periodoAcademico = periodoAcademico;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_ingreso", nullable=false, length=13)
    @NotNull
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="nota", nullable=false, precision=2)
    @NotNull
    public BigDecimal getNota() {
        return this.nota;
    }
    
    public void setNota(BigDecimal nota) {
        this.nota = nota;
    }




}


