package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Evaluacion generated by hbm2java
 */
@Entity
@Table(name="evaluacion"
)
public class Evaluacion  implements java.io.Serializable {


     private long idEvaluacion;
     private TipoEvaluacion tipoEvaluacion;
     private SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso;
     private Date fechaProgramada;
     private Date fechaEvaluacion;
     private String etiqueta;
     private Set<MaterialEvaluacion> materialEvaluacions = new HashSet<MaterialEvaluacion>(0);
     private Set<EvaluacionAlumno> evaluacionAlumnos = new HashSet<EvaluacionAlumno>(0);

    public Evaluacion() {
    }

	
    public Evaluacion(long idEvaluacion, TipoEvaluacion tipoEvaluacion, SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso, Date fechaProgramada, Date fechaEvaluacion, String etiqueta) {
        this.idEvaluacion = idEvaluacion;
        this.tipoEvaluacion = tipoEvaluacion;
        this.subPeriodoAcademicoSeccionCurso = subPeriodoAcademicoSeccionCurso;
        this.fechaEvaluacion = fechaEvaluacion;
        this.fechaProgramada = fechaProgramada;
        this.etiqueta = etiqueta;
    }
    public Evaluacion(long idEvaluacion, TipoEvaluacion tipoEvaluacion, SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso, Date fechaProgramada, String etiqueta, Set<MaterialEvaluacion> materialEvaluacions, Set<EvaluacionAlumno> evaluacionAlumnos) {
       this.idEvaluacion = idEvaluacion;
       this.tipoEvaluacion = tipoEvaluacion;
       this.subPeriodoAcademicoSeccionCurso = subPeriodoAcademicoSeccionCurso;
       this.fechaProgramada = fechaProgramada;
       this.etiqueta = etiqueta;
       this.materialEvaluacions = materialEvaluacions;
       this.evaluacionAlumnos = evaluacionAlumnos;
    }
   
     @Id 

    
    @Column(name="id_evaluacion", unique=true, nullable=false)
    public long getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(long idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_evaluacion", nullable=false)
    @NotNull
    public TipoEvaluacion getTipoEvaluacion() {
        return this.tipoEvaluacion;
    }
    
    public void setTipoEvaluacion(TipoEvaluacion tipoEvaluacion) {
        this.tipoEvaluacion = tipoEvaluacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_periodo_academico_seccion_curso", nullable=false)
    @NotNull
    public SubPeriodoAcademicoSeccionCurso getSubPeriodoAcademicoSeccionCurso() {
        return this.subPeriodoAcademicoSeccionCurso;
    }
    
    public void setSubPeriodoAcademicoSeccionCurso(SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso) {
        this.subPeriodoAcademicoSeccionCurso = subPeriodoAcademicoSeccionCurso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_programada", nullable=false, length=13)
    @NotNull
    public Date getFechaProgramada() {
        return this.fechaProgramada;
    }
    
    public void setFechaProgramada(Date fechaProgramada) {
        this.fechaProgramada = fechaProgramada;
    }

    
    
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_evaluacion", nullable=false, length=13)
    //@NotNull
    public Date getFechaEvaluacion() {
		return fechaEvaluacion;
	}


	public void setFechaEvaluacion(Date fechaEvaluacion) {
		this.fechaEvaluacion = fechaEvaluacion;
	}


	@Column(name="etiqueta", nullable=false, length=2)
    @NotNull
    @Length(max=2)
    public String getEtiqueta() {
        return this.etiqueta;
    }
    
    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evaluacion")
    public Set<MaterialEvaluacion> getMaterialEvaluacions() {
        return this.materialEvaluacions;
    }
    
    public void setMaterialEvaluacions(Set<MaterialEvaluacion> materialEvaluacions) {
        this.materialEvaluacions = materialEvaluacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evaluacion")
    public Set<EvaluacionAlumno> getEvaluacionAlumnos() {
        return this.evaluacionAlumnos;
    }
    
    public void setEvaluacionAlumnos(Set<EvaluacionAlumno> evaluacionAlumnos) {
        this.evaluacionAlumnos = evaluacionAlumnos;
    }




}


