package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * FotoPersona generated by hbm2java
 */
@Entity
@Table(name="foto_persona"
)
public class FotoPersona  implements java.io.Serializable {


     private long idFoto;
     private RepositorioArchivos repositorioArchivos;
     private Persona persona;
     private char vigente;
     private String nombreArchivo;

    public FotoPersona() {
    }

    public FotoPersona(long idFoto, RepositorioArchivos repositorioArchivos, Persona persona, char vigente, String nombreArchivo) {
       this.idFoto = idFoto;
       this.repositorioArchivos = repositorioArchivos;
       this.persona = persona;
       this.vigente = vigente;
       this.nombreArchivo = nombreArchivo;
    }
   
     @Id 

    
    @Column(name="id_foto", unique=true, nullable=false)
    public long getIdFoto() {
        return this.idFoto;
    }
    
    public void setIdFoto(long idFoto) {
        this.idFoto = idFoto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_repositorio", nullable=false)
    @NotNull
    public RepositorioArchivos getRepositorioArchivos() {
        return this.repositorioArchivos;
    }
    
    public void setRepositorioArchivos(RepositorioArchivos repositorioArchivos) {
        this.repositorioArchivos = repositorioArchivos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_persona", nullable=false)
    @NotNull
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="vigente", nullable=false, length=1)
    public char getVigente() {
        return this.vigente;
    }
    
    public void setVigente(char vigente) {
        this.vigente = vigente;
    }

    
    @Column(name="nombre_archivo", nullable=false, length=20)
    @NotNull
    @Length(max=20)
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }
    
    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }




}


