package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MaterialAsignacionId generated by hbm2java
 */
@Embeddable
public class MaterialAsignacionId  implements java.io.Serializable {


     private long idMaterial;
     private long idAsignacion;

    public MaterialAsignacionId() {
    }

    public MaterialAsignacionId(long idMaterial, long idAsignacion) {
       this.idMaterial = idMaterial;
       this.idAsignacion = idAsignacion;
    }
   


    @Column(name="id_material", nullable=false)
    public long getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(long idMaterial) {
        this.idMaterial = idMaterial;
    }


    @Column(name="id_asignacion", nullable=false)
    public long getIdAsignacion() {
        return this.idAsignacion;
    }
    
    public void setIdAsignacion(long idAsignacion) {
        this.idAsignacion = idAsignacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MaterialAsignacionId) ) return false;
		 MaterialAsignacionId castOther = ( MaterialAsignacionId ) other; 
         
		 return (this.getIdMaterial()==castOther.getIdMaterial())
 && (this.getIdAsignacion()==castOther.getIdAsignacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdMaterial();
         result = 37 * result + (int) this.getIdAsignacion();
         return result;
   }   


}


