package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * MaterialEvaluacion generated by hbm2java
 */
@Entity
@Table(name="material_evaluacion"
)
public class MaterialEvaluacion  implements java.io.Serializable {


     private MaterialEvaluacionId id;
     private Evaluacion evaluacion;
     private Materiales materiales;

    public MaterialEvaluacion() {
    }

    public MaterialEvaluacion(MaterialEvaluacionId id, Evaluacion evaluacion, Materiales materiales) {
       this.id = id;
       this.evaluacion = evaluacion;
       this.materiales = materiales;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idMaterial", column=@Column(name="id_material", nullable=false) ), 
        @AttributeOverride(name="idEvaluacion", column=@Column(name="id_evaluacion", nullable=false) ) } )
    @NotNull
    public MaterialEvaluacionId getId() {
        return this.id;
    }
    
    public void setId(MaterialEvaluacionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_evaluacion", nullable=false, insertable=false, updatable=false)
    @NotNull
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_material", nullable=false, insertable=false, updatable=false)
    @NotNull
    public Materiales getMateriales() {
        return this.materiales;
    }
    
    public void setMateriales(Materiales materiales) {
        this.materiales = materiales;
    }




}


