package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * MaterialAsignacion generated by hbm2java
 */
@Entity
@Table(name="material_asignacion"
)
public class MaterialAsignacion  implements java.io.Serializable {


     private MaterialAsignacionId id;
     private Asignacion asignacion;
     private Materiales materiales;

    public MaterialAsignacion() {
    }

    public MaterialAsignacion(MaterialAsignacionId id, Asignacion asignacion, Materiales materiales) {
       this.id = id;
       this.asignacion = asignacion;
       this.materiales = materiales;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idMaterial", column=@Column(name="id_material", nullable=false) ), 
        @AttributeOverride(name="idAsignacion", column=@Column(name="id_asignacion", nullable=false) ) } )
    @NotNull
    public MaterialAsignacionId getId() {
        return this.id;
    }
    
    public void setId(MaterialAsignacionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_asignacion", nullable=false, insertable=false, updatable=false)
    @NotNull
    public Asignacion getAsignacion() {
        return this.asignacion;
    }
    
    public void setAsignacion(Asignacion asignacion) {
        this.asignacion = asignacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_material", nullable=false, insertable=false, updatable=false)
    @NotNull
    public Materiales getMateriales() {
        return this.materiales;
    }
    
    public void setMateriales(Materiales materiales) {
        this.materiales = materiales;
    }




}


