package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MensajeDestinatarioId generated by hbm2java
 */
@Embeddable
public class MensajeDestinatarioId  implements java.io.Serializable {


     private long idMensaje;
     private long idPersona;

    public MensajeDestinatarioId() {
    }

    public MensajeDestinatarioId(long idMensaje, long idPersona) {
       this.idMensaje = idMensaje;
       this.idPersona = idPersona;
    }
   


    @Column(name="id_mensaje", nullable=false)
    public long getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(long idMensaje) {
        this.idMensaje = idMensaje;
    }


    @Column(name="id_persona", nullable=false)
    public long getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(long idPersona) {
        this.idPersona = idPersona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MensajeDestinatarioId) ) return false;
		 MensajeDestinatarioId castOther = ( MensajeDestinatarioId ) other; 
         
		 return (this.getIdMensaje()==castOther.getIdMensaje())
 && (this.getIdPersona()==castOther.getIdPersona());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdMensaje();
         result = 37 * result + (int) this.getIdPersona();
         return result;
   }   


}


