package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PeriodoAcademico generated by hbm2java
 */
@Entity
@Table(name="periodo_academico"
)
public class PeriodoAcademico  implements java.io.Serializable {


     private long idPeriodoAcademico;
     private Colegio colegio;
     private PeriodoAcademico periodoAcademico;
     private char enCurso;
     private String etiqueta;
     private Date fechaInicio;
     private Date fechaFin;
     private Set<Aviso> avisos = new HashSet<Aviso>(0);
     private Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos = new HashSet<SubPeriodoAcademicoSeccionCurso>(0);
     private Set<LibretaNotasSubperiodo> libretaNotasSubperiodos = new HashSet<LibretaNotasSubperiodo>(0);
     private Set<ResumenAlumno> resumenAlumnos = new HashSet<ResumenAlumno>(0);
     private Set<PeriodoAcademicoSeccion> periodoAcademicoSeccions = new HashSet<PeriodoAcademicoSeccion>(0);
     private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);
     private Set<ReciboPension> reciboPensions = new HashSet<ReciboPension>(0);
     private Set<EvaluacionAlumno> evaluacionAlumnos = new HashSet<EvaluacionAlumno>(0);
     private Set<LibretaNotas> libretaNotases = new HashSet<LibretaNotas>(0);
     private Set<AsignacionAlumno> asignacionAlumnos = new HashSet<AsignacionAlumno>(0);
     private Set<PeriodoAcademico> periodoAcademicos = new HashSet<PeriodoAcademico>(0);

    public PeriodoAcademico() {
    }

	
    public PeriodoAcademico(long idPeriodoAcademico, Colegio colegio, char enCurso, String etiqueta, Date fechaInicio, Date fechaFin) {
        this.idPeriodoAcademico = idPeriodoAcademico;
        this.colegio = colegio;
        this.enCurso = enCurso;
        this.etiqueta = etiqueta;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }
    public PeriodoAcademico(long idPeriodoAcademico, Colegio colegio, PeriodoAcademico periodoAcademico, char enCurso, String etiqueta, Date fechaInicio, Date fechaFin, Set<Aviso> avisos, Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos, Set<LibretaNotasSubperiodo> libretaNotasSubperiodos, Set<ResumenAlumno> resumenAlumnos, Set<PeriodoAcademicoSeccion> periodoAcademicoSeccions, Set<Asistencia> asistencias, Set<ReciboPension> reciboPensions, Set<EvaluacionAlumno> evaluacionAlumnos, Set<LibretaNotas> libretaNotases, Set<AsignacionAlumno> asignacionAlumnos, Set<PeriodoAcademico> periodoAcademicos) {
       this.idPeriodoAcademico = idPeriodoAcademico;
       this.colegio = colegio;
       this.periodoAcademico = periodoAcademico;
       this.enCurso = enCurso;
       this.etiqueta = etiqueta;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.avisos = avisos;
       this.subPeriodoAcademicoSeccionCursos = subPeriodoAcademicoSeccionCursos;
       this.libretaNotasSubperiodos = libretaNotasSubperiodos;
       this.resumenAlumnos = resumenAlumnos;
       this.periodoAcademicoSeccions = periodoAcademicoSeccions;
       this.asistencias = asistencias;
       this.reciboPensions = reciboPensions;
       this.evaluacionAlumnos = evaluacionAlumnos;
       this.libretaNotases = libretaNotases;
       this.asignacionAlumnos = asignacionAlumnos;
       this.periodoAcademicos = periodoAcademicos;
    }
   
     @Id 

    
    @Column(name="id_periodo_academico", unique=true, nullable=false)
    public long getIdPeriodoAcademico() {
        return this.idPeriodoAcademico;
    }
    
    public void setIdPeriodoAcademico(long idPeriodoAcademico) {
        this.idPeriodoAcademico = idPeriodoAcademico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_colegio", nullable=false)
    @NotNull
    public Colegio getColegio() {
        return this.colegio;
    }
    
    public void setColegio(Colegio colegio) {
        this.colegio = colegio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_parent")
    public PeriodoAcademico getPeriodoAcademico() {
        return this.periodoAcademico;
    }
    
    public void setPeriodoAcademico(PeriodoAcademico periodoAcademico) {
        this.periodoAcademico = periodoAcademico;
    }

    
    @Column(name="en_curso", nullable=false, length=1)
    public char getEnCurso() {
        return this.enCurso;
    }
    
    public void setEnCurso(char enCurso) {
        this.enCurso = enCurso;
    }

    
    @Column(name="etiqueta", nullable=false, length=40)
    @NotNull
    @Length(max=40)
    public String getEtiqueta() {
        return this.etiqueta;
    }
    
    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=13)
    @NotNull
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", nullable=false, length=13)
    @NotNull
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademico")
    public Set<Aviso> getAvisos() {
        return this.avisos;
    }
    
    public void setAvisos(Set<Aviso> avisos) {
        this.avisos = avisos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademico")
    public Set<SubPeriodoAcademicoSeccionCurso> getSubPeriodoAcademicoSeccionCursos() {
        return this.subPeriodoAcademicoSeccionCursos;
    }
    
    public void setSubPeriodoAcademicoSeccionCursos(Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos) {
        this.subPeriodoAcademicoSeccionCursos = subPeriodoAcademicoSeccionCursos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademico")
    public Set<LibretaNotasSubperiodo> getLibretaNotasSubperiodos() {
        return this.libretaNotasSubperiodos;
    }
    
    public void setLibretaNotasSubperiodos(Set<LibretaNotasSubperiodo> libretaNotasSubperiodos) {
        this.libretaNotasSubperiodos = libretaNotasSubperiodos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademico")
    public Set<ResumenAlumno> getResumenAlumnos() {
        return this.resumenAlumnos;
    }
    
    public void setResumenAlumnos(Set<ResumenAlumno> resumenAlumnos) {
        this.resumenAlumnos = resumenAlumnos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademico")
    public Set<PeriodoAcademicoSeccion> getPeriodoAcademicoSeccions() {
        return this.periodoAcademicoSeccions;
    }
    
    public void setPeriodoAcademicoSeccions(Set<PeriodoAcademicoSeccion> periodoAcademicoSeccions) {
        this.periodoAcademicoSeccions = periodoAcademicoSeccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademico")
    public Set<Asistencia> getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set<Asistencia> asistencias) {
        this.asistencias = asistencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademico")
    public Set<ReciboPension> getReciboPensions() {
        return this.reciboPensions;
    }
    
    public void setReciboPensions(Set<ReciboPension> reciboPensions) {
        this.reciboPensions = reciboPensions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademico")
    public Set<EvaluacionAlumno> getEvaluacionAlumnos() {
        return this.evaluacionAlumnos;
    }
    
    public void setEvaluacionAlumnos(Set<EvaluacionAlumno> evaluacionAlumnos) {
        this.evaluacionAlumnos = evaluacionAlumnos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademico")
    public Set<LibretaNotas> getLibretaNotases() {
        return this.libretaNotases;
    }
    
    public void setLibretaNotases(Set<LibretaNotas> libretaNotases) {
        this.libretaNotases = libretaNotases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademico")
    public Set<AsignacionAlumno> getAsignacionAlumnos() {
        return this.asignacionAlumnos;
    }
    
    public void setAsignacionAlumnos(Set<AsignacionAlumno> asignacionAlumnos) {
        this.asignacionAlumnos = asignacionAlumnos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademico")
    public Set<PeriodoAcademico> getPeriodoAcademicos() {
        return this.periodoAcademicos;
    }
    
    public void setPeriodoAcademicos(Set<PeriodoAcademico> periodoAcademicos) {
        this.periodoAcademicos = periodoAcademicos;
    }




}


