package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name="permiso"
)
public class Permiso  implements java.io.Serializable {


     private long idPermiso;
     private Persona personaByIdPersona;
     private Persona personaByPersonaIdRegistro;
     private Date fechaPermiso;
     private Date fechaRegistro;
     private String comentarios;

    public Permiso() {
    }

    public Permiso(long idPermiso, Persona personaByIdPersona, Persona personaByPersonaIdRegistro, Date fechaPermiso, Date fechaRegistro, String comentarios) {
       this.idPermiso = idPermiso;
       this.personaByIdPersona = personaByIdPersona;
       this.personaByPersonaIdRegistro = personaByPersonaIdRegistro;
       this.fechaPermiso = fechaPermiso;
       this.fechaRegistro = fechaRegistro;
       this.comentarios = comentarios;
    }
   
     @Id 

    
    @Column(name="id_permiso", unique=true, nullable=false)
    public long getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(long idPermiso) {
        this.idPermiso = idPermiso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_persona", nullable=false)
    @NotNull
    public Persona getPersonaByIdPersona() {
        return this.personaByIdPersona;
    }
    
    public void setPersonaByIdPersona(Persona personaByIdPersona) {
        this.personaByIdPersona = personaByIdPersona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="persona_id_registro", nullable=false)
    @NotNull
    public Persona getPersonaByPersonaIdRegistro() {
        return this.personaByPersonaIdRegistro;
    }
    
    public void setPersonaByPersonaIdRegistro(Persona personaByPersonaIdRegistro) {
        this.personaByPersonaIdRegistro = personaByPersonaIdRegistro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_permiso", nullable=false, length=13)
    @NotNull
    public Date getFechaPermiso() {
        return this.fechaPermiso;
    }
    
    public void setFechaPermiso(Date fechaPermiso) {
        this.fechaPermiso = fechaPermiso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_registro", nullable=false, length=13)
    @NotNull
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    
    @Column(name="comentarios", nullable=false, length=400)
    @NotNull
    @Length(max=400)
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }




}


