package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * PersonaMedioContacto generated by hbm2java
 */
@Entity
@Table(name="persona_medio_contacto"
)
public class PersonaMedioContacto  implements java.io.Serializable {


     private PersonaMedioContactoId id;
     private Persona persona;
     private MedioContacto medioContacto;

    public PersonaMedioContacto() {
    }

    public PersonaMedioContacto(PersonaMedioContactoId id, Persona persona, MedioContacto medioContacto) {
       this.id = id;
       this.persona = persona;
       this.medioContacto = medioContacto;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPersona", column=@Column(name="id_persona", nullable=false) ), 
        @AttributeOverride(name="idMedioContacto", column=@Column(name="id_medio_contacto", nullable=false) ), 
        @AttributeOverride(name="referencia", column=@Column(name="referencia", nullable=false) ) } )
    @NotNull
    public PersonaMedioContactoId getId() {
        return this.id;
    }
    
    public void setId(PersonaMedioContactoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_persona", nullable=false, insertable=false, updatable=false)
    @NotNull
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_medio_contacto", nullable=false, insertable=false, updatable=false)
    @NotNull
    public MedioContacto getMedioContacto() {
        return this.medioContacto;
    }
    
    public void setMedioContacto(MedioContacto medioContacto) {
        this.medioContacto = medioContacto;
    }




}


