package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * ReciboPension generated by hbm2java
 */
@Entity
@Table(name="recibo_pension"
)
public class ReciboPension  implements java.io.Serializable {


     private String idReciboPension;
     private Moneda moneda;
     private Alumno alumno;
     private PeriodoAcademico periodoAcademico;
     private CuentaBanco cuentaBanco;
     private Date fechaEmision;
     private Date fechaMaximaPago;
     private Date fechaPago;
     private long idColegio;
     private BigDecimal mora;
     private BigDecimal monto;
     private ReciboPensionDetalle reciboPensionDetalle;

    public ReciboPension() {
    }

	
    public ReciboPension(String idReciboPension, Moneda moneda, Alumno alumno, PeriodoAcademico periodoAcademico, CuentaBanco cuentaBanco, Date fechaEmision, Date fechaMaximaPago, long idColegio, BigDecimal mora, BigDecimal monto) {
        this.idReciboPension = idReciboPension;
        this.moneda = moneda;
        this.alumno = alumno;
        this.periodoAcademico = periodoAcademico;
        this.cuentaBanco = cuentaBanco;
        this.fechaEmision = fechaEmision;
        this.fechaMaximaPago = fechaMaximaPago;
        this.idColegio = idColegio;
        this.mora = mora;
        this.monto = monto;
    }
    public ReciboPension(String idReciboPension, Moneda moneda, Alumno alumno, PeriodoAcademico periodoAcademico, CuentaBanco cuentaBanco, Date fechaEmision, Date fechaMaximaPago, Date fechaPago, long idColegio, BigDecimal mora, BigDecimal monto, ReciboPensionDetalle reciboPensionDetalle) {
       this.idReciboPension = idReciboPension;
       this.moneda = moneda;
       this.alumno = alumno;
       this.periodoAcademico = periodoAcademico;
       this.cuentaBanco = cuentaBanco;
       this.fechaEmision = fechaEmision;
       this.fechaMaximaPago = fechaMaximaPago;
       this.fechaPago = fechaPago;
       this.idColegio = idColegio;
       this.mora = mora;
       this.monto = monto;
       this.reciboPensionDetalle = reciboPensionDetalle;
    }
   
     @Id 

    
    @Column(name="id_recibo_pension", unique=true, nullable=false)
    @NotNull
    public String getIdReciboPension() {
        return this.idReciboPension;
    }
    
    public void setIdReciboPension(String idReciboPension) {
        this.idReciboPension = idReciboPension;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_moneda", nullable=false)
    @NotNull
    public Moneda getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_alumno", nullable=false)
    @NotNull
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_periodo_academico", nullable=false)
    @NotNull
    public PeriodoAcademico getPeriodoAcademico() {
        return this.periodoAcademico;
    }
    
    public void setPeriodoAcademico(PeriodoAcademico periodoAcademico) {
        this.periodoAcademico = periodoAcademico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_banco", nullable=false)
    @NotNull
    public CuentaBanco getCuentaBanco() {
        return this.cuentaBanco;
    }
    
    public void setCuentaBanco(CuentaBanco cuentaBanco) {
        this.cuentaBanco = cuentaBanco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_emision", nullable=false, length=13)
    @NotNull
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_maxima_pago", nullable=false, length=13)
    @NotNull
    public Date getFechaMaximaPago() {
        return this.fechaMaximaPago;
    }
    
    public void setFechaMaximaPago(Date fechaMaximaPago) {
        this.fechaMaximaPago = fechaMaximaPago;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_pago", length=13)
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    
    @Column(name="id_colegio", nullable=false)
    public long getIdColegio() {
        return this.idColegio;
    }
    
    public void setIdColegio(long idColegio) {
        this.idColegio = idColegio;
    }

    
    @Column(name="mora", nullable=false, precision=4)
    @NotNull
    public BigDecimal getMora() {
        return this.mora;
    }
    
    public void setMora(BigDecimal mora) {
        this.mora = mora;
    }

    
    @Column(name="monto", nullable=false, precision=10)
    @NotNull
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="reciboPension")
    public ReciboPensionDetalle getReciboPensionDetalle() {
        return this.reciboPensionDetalle;
    }
    
    public void setReciboPensionDetalle(ReciboPensionDetalle reciboPensionDetalle) {
        this.reciboPensionDetalle = reciboPensionDetalle;
    }




}


