package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * ReciboPensionDetalle generated by hbm2java
 */
@Entity
@Table(name="recibo_pension_detalle"
)
public class ReciboPensionDetalle  implements java.io.Serializable {


     private String idReciboPension;
     private ReciboPension reciboPension;
     private Concepto concepto;
     private short cantidad;
     private BigDecimal precio;

    public ReciboPensionDetalle() {
    }

    public ReciboPensionDetalle(ReciboPension reciboPension, Concepto concepto, short cantidad, BigDecimal precio) {
       this.reciboPension = reciboPension;
       this.concepto = concepto;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="reciboPension"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id_recibo_pension", unique=true, nullable=false)
    public String getIdReciboPension() {
        return this.idReciboPension;
    }
    
    public void setIdReciboPension(String idReciboPension) {
        this.idReciboPension = idReciboPension;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    @NotNull
    public ReciboPension getReciboPension() {
        return this.reciboPension;
    }
    
    public void setReciboPension(ReciboPension reciboPension) {
        this.reciboPension = reciboPension;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_concepto", nullable=false)
    @NotNull
    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }

    
    @Column(name="cantidad", nullable=false)
    public short getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(short cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="precio", nullable=false, precision=10)
    @NotNull
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


