package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Seccion generated by hbm2java
 */
@Entity
@Table(name="seccion"
)
public class Seccion  implements java.io.Serializable {


     private long idSeccion;
     private Colegio colegio;
     private Grado grado;
     private int correlativo;
     private String etiqueta;
     private Set<AvisoSeccion> avisoSeccions = new HashSet<AvisoSeccion>(0);
     private Set<PeriodoAcademicoSeccion> periodoAcademicoSeccions = new HashSet<PeriodoAcademicoSeccion>(0);
     private Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos = new HashSet<SubPeriodoAcademicoSeccionCurso>(0);
     private Set<ResumenAlumno> resumenAlumnos = new HashSet<ResumenAlumno>(0);
     private Set<PeriodoAcademicoSeccionCurso> periodoAcademicoSeccionCursos = new HashSet<PeriodoAcademicoSeccionCurso>(0);
     private Set<LibretaNotas> libretaNotases = new HashSet<LibretaNotas>(0);

    public Seccion() {
    }

	
    public Seccion(long idSeccion, Colegio colegio, Grado grado, int correlativo, String etiqueta) {
        this.idSeccion = idSeccion;
        this.colegio = colegio;
        this.grado = grado;
        this.correlativo = correlativo;
        this.etiqueta = etiqueta;
    }
    public Seccion(long idSeccion, Colegio colegio, Grado grado, int correlativo, String etiqueta, Set<AvisoSeccion> avisoSeccions, Set<PeriodoAcademicoSeccion> periodoAcademicoSeccions, Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos, Set<ResumenAlumno> resumenAlumnos, Set<PeriodoAcademicoSeccionCurso> periodoAcademicoSeccionCursos, Set<LibretaNotas> libretaNotases) {
       this.idSeccion = idSeccion;
       this.colegio = colegio;
       this.grado = grado;
       this.correlativo = correlativo;
       this.etiqueta = etiqueta;
       this.avisoSeccions = avisoSeccions;
       this.periodoAcademicoSeccions = periodoAcademicoSeccions;
       this.subPeriodoAcademicoSeccionCursos = subPeriodoAcademicoSeccionCursos;
       this.resumenAlumnos = resumenAlumnos;
       this.periodoAcademicoSeccionCursos = periodoAcademicoSeccionCursos;
       this.libretaNotases = libretaNotases;
    }
   
     @Id 

    
    @Column(name="id_seccion", unique=true, nullable=false)
    public long getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(long idSeccion) {
        this.idSeccion = idSeccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_colegio", nullable=false)
    @NotNull
    public Colegio getColegio() {
        return this.colegio;
    }
    
    public void setColegio(Colegio colegio) {
        this.colegio = colegio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_grado", nullable=false)
    @NotNull
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }

    
    @Column(name="correlativo", nullable=false)
    public int getCorrelativo() {
        return this.correlativo;
    }
    
    public void setCorrelativo(int correlativo) {
        this.correlativo = correlativo;
    }

    
    @Column(name="etiqueta", nullable=false, length=6)
    @NotNull
    @Length(max=6)
    public String getEtiqueta() {
        return this.etiqueta;
    }
    
    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seccion")
    public Set<AvisoSeccion> getAvisoSeccions() {
        return this.avisoSeccions;
    }
    
    public void setAvisoSeccions(Set<AvisoSeccion> avisoSeccions) {
        this.avisoSeccions = avisoSeccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seccion")
    public Set<PeriodoAcademicoSeccion> getPeriodoAcademicoSeccions() {
        return this.periodoAcademicoSeccions;
    }
    
    public void setPeriodoAcademicoSeccions(Set<PeriodoAcademicoSeccion> periodoAcademicoSeccions) {
        this.periodoAcademicoSeccions = periodoAcademicoSeccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seccion")
    public Set<SubPeriodoAcademicoSeccionCurso> getSubPeriodoAcademicoSeccionCursos() {
        return this.subPeriodoAcademicoSeccionCursos;
    }
    
    public void setSubPeriodoAcademicoSeccionCursos(Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos) {
        this.subPeriodoAcademicoSeccionCursos = subPeriodoAcademicoSeccionCursos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seccion")
    public Set<ResumenAlumno> getResumenAlumnos() {
        return this.resumenAlumnos;
    }
    
    public void setResumenAlumnos(Set<ResumenAlumno> resumenAlumnos) {
        this.resumenAlumnos = resumenAlumnos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seccion")
    public Set<PeriodoAcademicoSeccionCurso> getPeriodoAcademicoSeccionCursos() {
        return this.periodoAcademicoSeccionCursos;
    }
    
    public void setPeriodoAcademicoSeccionCursos(Set<PeriodoAcademicoSeccionCurso> periodoAcademicoSeccionCursos) {
        this.periodoAcademicoSeccionCursos = periodoAcademicoSeccionCursos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seccion")
    public Set<LibretaNotas> getLibretaNotases() {
        return this.libretaNotases;
    }
    
    public void setLibretaNotases(Set<LibretaNotas> libretaNotases) {
        this.libretaNotases = libretaNotases;
    }




}


