package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SubPeriodoAcademicoSeccionCurso generated by hbm2java
 */
@Entity
@Table(name="sub_periodo_academico_seccion_curso"
)
public class SubPeriodoAcademicoSeccionCurso  implements java.io.Serializable {


     private long idSubPeriodoAcademicoSeccionCurso;
     private Seccion seccion;
     private PeriodoAcademico periodoAcademico;
     private Curso curso;
     private PeriodoAcademicoSeccionCurso periodoAcademicoSeccionCurso;
     private String formulaNotaSubPeriodo;
     private Set<Asignacion> asignacions = new HashSet<Asignacion>(0);
     private Set<Materiales> materialeses = new HashSet<Materiales>(0);
     private Set<Evaluacion> evaluacions = new HashSet<Evaluacion>(0);
     private Set<LibretaNotasSubperiodo> libretaNotasSubperiodos = new HashSet<LibretaNotasSubperiodo>(0);
     private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);

    public SubPeriodoAcademicoSeccionCurso() {
    }

	
    public SubPeriodoAcademicoSeccionCurso(long idSubPeriodoAcademicoSeccionCurso, Seccion seccion, PeriodoAcademico periodoAcademico, Curso curso, PeriodoAcademicoSeccionCurso periodoAcademicoSeccionCurso, String formulaNotaSubPeriodo) {
        this.idSubPeriodoAcademicoSeccionCurso = idSubPeriodoAcademicoSeccionCurso;
        this.seccion = seccion;
        this.periodoAcademico = periodoAcademico;
        this.curso = curso;
        this.periodoAcademicoSeccionCurso = periodoAcademicoSeccionCurso;
        this.formulaNotaSubPeriodo = formulaNotaSubPeriodo;
    }
    public SubPeriodoAcademicoSeccionCurso(long idSubPeriodoAcademicoSeccionCurso, Seccion seccion, PeriodoAcademico periodoAcademico, Curso curso, PeriodoAcademicoSeccionCurso periodoAcademicoSeccionCurso, String formulaNotaSubPeriodo, Set<Asignacion> asignacions, Set<Materiales> materialeses, Set<Evaluacion> evaluacions, Set<LibretaNotasSubperiodo> libretaNotasSubperiodos, Set<Asistencia> asistencias) {
       this.idSubPeriodoAcademicoSeccionCurso = idSubPeriodoAcademicoSeccionCurso;
       this.seccion = seccion;
       this.periodoAcademico = periodoAcademico;
       this.curso = curso;
       this.periodoAcademicoSeccionCurso = periodoAcademicoSeccionCurso;
       this.formulaNotaSubPeriodo = formulaNotaSubPeriodo;
       this.asignacions = asignacions;
       this.materialeses = materialeses;
       this.evaluacions = evaluacions;
       this.libretaNotasSubperiodos = libretaNotasSubperiodos;
       this.asistencias = asistencias;
    }
   
     @Id 

    
    @Column(name="id_sub_periodo_academico_seccion_curso", unique=true, nullable=false)
    public long getIdSubPeriodoAcademicoSeccionCurso() {
        return this.idSubPeriodoAcademicoSeccionCurso;
    }
    
    public void setIdSubPeriodoAcademicoSeccionCurso(long idSubPeriodoAcademicoSeccionCurso) {
        this.idSubPeriodoAcademicoSeccionCurso = idSubPeriodoAcademicoSeccionCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_seccion", nullable=false)
    @NotNull
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_periodo_academico", nullable=false)
    @NotNull
    public PeriodoAcademico getPeriodoAcademico() {
        return this.periodoAcademico;
    }
    
    public void setPeriodoAcademico(PeriodoAcademico periodoAcademico) {
        this.periodoAcademico = periodoAcademico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_curso", nullable=false)
    @NotNull
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_periodo_academico_seccion_curso", nullable=false)
    @NotNull
    public PeriodoAcademicoSeccionCurso getPeriodoAcademicoSeccionCurso() {
        return this.periodoAcademicoSeccionCurso;
    }
    
    public void setPeriodoAcademicoSeccionCurso(PeriodoAcademicoSeccionCurso periodoAcademicoSeccionCurso) {
        this.periodoAcademicoSeccionCurso = periodoAcademicoSeccionCurso;
    }

    
    @Column(name="formula_nota_sub_periodo", nullable=false, length=50)
    @NotNull
    @Length(max=50)
    public String getFormulaNotaSubPeriodo() {
        return this.formulaNotaSubPeriodo;
    }
    
    public void setFormulaNotaSubPeriodo(String formulaNotaSubPeriodo) {
        this.formulaNotaSubPeriodo = formulaNotaSubPeriodo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subPeriodoAcademicoSeccionCurso")
    public Set<Asignacion> getAsignacions() {
        return this.asignacions;
    }
    
    public void setAsignacions(Set<Asignacion> asignacions) {
        this.asignacions = asignacions;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="subPeriodoAcademicoSeccionCursos")
    public Set<Materiales> getMaterialeses() {
        return this.materialeses;
    }
    
    public void setMaterialeses(Set<Materiales> materialeses) {
        this.materialeses = materialeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subPeriodoAcademicoSeccionCurso")
    public Set<Evaluacion> getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set<Evaluacion> evaluacions) {
        this.evaluacions = evaluacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subPeriodoAcademicoSeccionCurso")
    public Set<LibretaNotasSubperiodo> getLibretaNotasSubperiodos() {
        return this.libretaNotasSubperiodos;
    }
    
    public void setLibretaNotasSubperiodos(Set<LibretaNotasSubperiodo> libretaNotasSubperiodos) {
        this.libretaNotasSubperiodos = libretaNotasSubperiodos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subPeriodoAcademicoSeccionCurso")
    public Set<Asistencia> getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set<Asistencia> asistencias) {
        this.asistencias = asistencias;
    }




}


