package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoAsignacion generated by hbm2java
 */
@Entity
@Table(name="tipo_asignacion"
)
public class TipoAsignacion  implements java.io.Serializable {


     private short idTipoAsignacion;
     private Colegio colegio;
     private String nombre;
     private Set<Asignacion> asignacions = new HashSet<Asignacion>(0);

    public TipoAsignacion() {
    }

	
    public TipoAsignacion(short idTipoAsignacion, Colegio colegio, String nombre) {
        this.idTipoAsignacion = idTipoAsignacion;
        this.colegio = colegio;
        this.nombre = nombre;
    }
    public TipoAsignacion(short idTipoAsignacion, Colegio colegio, String nombre, Set<Asignacion> asignacions) {
       this.idTipoAsignacion = idTipoAsignacion;
       this.colegio = colegio;
       this.nombre = nombre;
       this.asignacions = asignacions;
    }
   
     @Id 

    
    @Column(name="id_tipo_asignacion", unique=true, nullable=false)
    public short getIdTipoAsignacion() {
        return this.idTipoAsignacion;
    }
    
    public void setIdTipoAsignacion(short idTipoAsignacion) {
        this.idTipoAsignacion = idTipoAsignacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_colegio", nullable=false)
    @NotNull
    public Colegio getColegio() {
        return this.colegio;
    }
    
    public void setColegio(Colegio colegio) {
        this.colegio = colegio;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    @NotNull
    @Length(max=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoAsignacion")
    public Set<Asignacion> getAsignacions() {
        return this.asignacions;
    }
    
    public void setAsignacions(Set<Asignacion> asignacions) {
        this.asignacions = asignacions;
    }




}


