package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoApoderado generated by hbm2java
 */
@Entity
@Table(name="tipo_apoderado"
)
public class TipoApoderado  implements java.io.Serializable {


     private short idTipoApoderado;
     private String nombre;
     private Set<Apoderado> apoderados = new HashSet<Apoderado>(0);

    public TipoApoderado() {
    }

	
    public TipoApoderado(short idTipoApoderado, String nombre) {
        this.idTipoApoderado = idTipoApoderado;
        this.nombre = nombre;
    }
    public TipoApoderado(short idTipoApoderado, String nombre, Set<Apoderado> apoderados) {
       this.idTipoApoderado = idTipoApoderado;
       this.nombre = nombre;
       this.apoderados = apoderados;
    }
   
     @Id 

    
    @Column(name="id_tipo_apoderado", unique=true, nullable=false)
    public short getIdTipoApoderado() {
        return this.idTipoApoderado;
    }
    
    public void setIdTipoApoderado(short idTipoApoderado) {
        this.idTipoApoderado = idTipoApoderado;
    }

    
    @Column(name="nombre", nullable=false, length=20)
    @NotNull
    @Length(max=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoApoderado")
    public Set<Apoderado> getApoderados() {
        return this.apoderados;
    }
    
    public void setApoderados(Set<Apoderado> apoderados) {
        this.apoderados = apoderados;
    }




}


