package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Asignacion generated by hbm2java
 */
@Entity
@Table(name="asignacion"
)
public class Asignacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -6742417556696889944L;
	private long idAsignacion;
     private TipoAsignacion tipoAsignacion;
     private SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso;
     private String descripcion;
     private Date fechaEntrega;
     private String etiqueta;
     private Set<AsignacionAlumno> asignacionAlumnos = new HashSet<AsignacionAlumno>(0);
     private Set<MaterialAsignacion> materialAsignacions = new HashSet<MaterialAsignacion>(0);

    public Asignacion() {
    }

	
    public Asignacion(long idAsignacion, TipoAsignacion tipoAsignacion, SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso, String descripcion, Date fechaEntrega, String etiqueta) {
        this.idAsignacion = idAsignacion;
        this.tipoAsignacion = tipoAsignacion;
        this.subPeriodoAcademicoSeccionCurso = subPeriodoAcademicoSeccionCurso;
        this.descripcion = descripcion;
        this.fechaEntrega = fechaEntrega;
        this.etiqueta = etiqueta;
    }
    public Asignacion(long idAsignacion, TipoAsignacion tipoAsignacion, SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso, String descripcion, Date fechaEntrega, String etiqueta, Set<AsignacionAlumno> asignacionAlumnos, Set<MaterialAsignacion> materialAsignacions) {
       this.idAsignacion = idAsignacion;
       this.tipoAsignacion = tipoAsignacion;
       this.subPeriodoAcademicoSeccionCurso = subPeriodoAcademicoSeccionCurso;
       this.descripcion = descripcion;
       this.fechaEntrega = fechaEntrega;
       this.etiqueta = etiqueta;
       this.asignacionAlumnos = asignacionAlumnos;
       this.materialAsignacions = materialAsignacions;
    }
   
     @Id 

    
    @Column(name="id_asignacion", unique=true, nullable=false)
    public long getIdAsignacion() {
        return this.idAsignacion;
    }
    
    public void setIdAsignacion(long idAsignacion) {
        this.idAsignacion = idAsignacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_asignacion", nullable=false)
    @NotNull
    public TipoAsignacion getTipoAsignacion() {
        return this.tipoAsignacion;
    }
    
    public void setTipoAsignacion(TipoAsignacion tipoAsignacion) {
        this.tipoAsignacion = tipoAsignacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_periodo_academico_seccion_curso", nullable=false)
    @NotNull
    public SubPeriodoAcademicoSeccionCurso getSubPeriodoAcademicoSeccionCurso() {
        return this.subPeriodoAcademicoSeccionCurso;
    }
    
    public void setSubPeriodoAcademicoSeccionCurso(SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso) {
        this.subPeriodoAcademicoSeccionCurso = subPeriodoAcademicoSeccionCurso;
    }

    
    @Column(name="descripcion", nullable=false)
    @NotNull
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_entrega", nullable=false, length=13)
    @NotNull
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }

    
    @Column(name="etiqueta", nullable=false, length=2)
    @NotNull
    @Length(max=2)
    public String getEtiqueta() {
        return this.etiqueta;
    }
    
    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="asignacion")
    public Set<AsignacionAlumno> getAsignacionAlumnos() {
        return this.asignacionAlumnos;
    }
    
    public void setAsignacionAlumnos(Set<AsignacionAlumno> asignacionAlumnos) {
        this.asignacionAlumnos = asignacionAlumnos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="asignacion")
    public Set<MaterialAsignacion> getMaterialAsignacions() {
        return this.materialAsignacions;
    }
    
    public void setMaterialAsignacions(Set<MaterialAsignacion> materialAsignacions) {
        this.materialAsignacions = materialAsignacions;
    }




}


