package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Asistencia generated by hbm2java
 */
@Entity
@Table(name="asistencia"
)
public class Asistencia  implements java.io.Serializable {


     private long idAsistencia;
     private Justificacion justificacion;
     private PeriodoAcademico periodoAcademico;
     private Curso curso;
     private Alumno alumno;
     private SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso;
     private Date fecha;
     private char asistio;
     private char justificada;

    public Asistencia() {
    }

	
    public Asistencia(long idAsistencia, PeriodoAcademico periodoAcademico, Curso curso, Alumno alumno, SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso, Date fecha, char asistio, char justificada) {
        this.idAsistencia = idAsistencia;
        this.periodoAcademico = periodoAcademico;
        this.curso = curso;
        this.alumno = alumno;
        this.subPeriodoAcademicoSeccionCurso = subPeriodoAcademicoSeccionCurso;
        this.fecha = fecha;
        this.asistio = asistio;
        this.justificada = justificada;
    }
    public Asistencia(long idAsistencia, Justificacion justificacion, PeriodoAcademico periodoAcademico, Curso curso, Alumno alumno, SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso, Date fecha, char asistio, char justificada) {
       this.idAsistencia = idAsistencia;
       this.justificacion = justificacion;
       this.periodoAcademico = periodoAcademico;
       this.curso = curso;
       this.alumno = alumno;
       this.subPeriodoAcademicoSeccionCurso = subPeriodoAcademicoSeccionCurso;
       this.fecha = fecha;
       this.asistio = asistio;
       this.justificada = justificada;
    }
   
     @Id
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id_asistencia", unique=true, nullable=false)
    public long getIdAsistencia() {
        return this.idAsistencia;
    }
    
    public void setIdAsistencia(long idAsistencia) {
        this.idAsistencia = idAsistencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_justificacion")
    public Justificacion getJustificacion() {
        return this.justificacion;
    }
    
    public void setJustificacion(Justificacion justificacion) {
        this.justificacion = justificacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_periodo_academico", nullable=false)
    @NotNull
    public PeriodoAcademico getPeriodoAcademico() {
        return this.periodoAcademico;
    }
    
    public void setPeriodoAcademico(PeriodoAcademico periodoAcademico) {
        this.periodoAcademico = periodoAcademico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_curso", nullable=false)
    @NotNull
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_alumno", nullable=false)
    @NotNull
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_periodo_academico_seccion_curso", nullable=false)
    @NotNull
    public SubPeriodoAcademicoSeccionCurso getSubPeriodoAcademicoSeccionCurso() {
        return this.subPeriodoAcademicoSeccionCurso;
    }
    
    public void setSubPeriodoAcademicoSeccionCurso(SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso) {
        this.subPeriodoAcademicoSeccionCurso = subPeriodoAcademicoSeccionCurso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    @NotNull
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="asistio", nullable=false, length=1)
    public char getAsistio() {
        return this.asistio;
    }
    
    public void setAsistio(char asistio) {
        this.asistio = asistio;
    }

    
    @Column(name="justificada", nullable=false, length=1)
    public char getJustificada() {
        return this.justificada;
    }
    
    public void setJustificada(char justificada) {
        this.justificada = justificada;
    }




}


