package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Aviso generated by hbm2java
 */
@Entity
@Table(name="aviso"
)
public class Aviso  implements java.io.Serializable {


     private long idAviso;
     private Colegio colegio;
     private PeriodoAcademico periodoAcademico;
     private String nombre;
     private String descripcion;
     private String lugar;
     private Date fechaFinPublicacion;
     private Date fechaInicioPublicacion;
     private char general;
     private Set<AvisoSeccion> avisoSeccions = new HashSet<AvisoSeccion>(0);

    public Aviso() {
    }

	
    public Aviso(long idAviso, Colegio colegio, PeriodoAcademico periodoAcademico, String nombre, String descripcion, String lugar, Date fechaFinPublicacion, Date fechaInicioPublicacion, char general) {
        this.idAviso = idAviso;
        this.colegio = colegio;
        this.periodoAcademico = periodoAcademico;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.lugar = lugar;
        this.fechaFinPublicacion = fechaFinPublicacion;
        this.fechaInicioPublicacion = fechaInicioPublicacion;
        this.general = general;
    }
    public Aviso(long idAviso, Colegio colegio, PeriodoAcademico periodoAcademico, String nombre, String descripcion, String lugar, Date fechaFinPublicacion, Date fechaInicioPublicacion, char general, Set<AvisoSeccion> avisoSeccions) {
       this.idAviso = idAviso;
       this.colegio = colegio;
       this.periodoAcademico = periodoAcademico;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.lugar = lugar;
       this.fechaFinPublicacion = fechaFinPublicacion;
       this.fechaInicioPublicacion = fechaInicioPublicacion;
       this.general = general;
       this.avisoSeccions = avisoSeccions;
    }
   
     @Id 

    
    @Column(name="id_aviso", unique=true, nullable=false)
    public long getIdAviso() {
        return this.idAviso;
    }
    
    public void setIdAviso(long idAviso) {
        this.idAviso = idAviso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_colegio", nullable=false)
    @NotNull
    public Colegio getColegio() {
        return this.colegio;
    }
    
    public void setColegio(Colegio colegio) {
        this.colegio = colegio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_periodo_academico", nullable=false)
    @NotNull
    public PeriodoAcademico getPeriodoAcademico() {
        return this.periodoAcademico;
    }
    
    public void setPeriodoAcademico(PeriodoAcademico periodoAcademico) {
        this.periodoAcademico = periodoAcademico;
    }

    
    @Column(name="nombre", nullable=false, length=40)
    @NotNull
    @Length(max=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=500)
    @NotNull
    @Length(max=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="lugar", nullable=false, length=100)
    @NotNull
    @Length(max=100)
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin_publicacion", nullable=false, length=13)
    @NotNull
    public Date getFechaFinPublicacion() {
        return this.fechaFinPublicacion;
    }
    
    public void setFechaFinPublicacion(Date fechaFinPublicacion) {
        this.fechaFinPublicacion = fechaFinPublicacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio_publicacion", nullable=false, length=13)
    @NotNull
    public Date getFechaInicioPublicacion() {
        return this.fechaInicioPublicacion;
    }
    
    public void setFechaInicioPublicacion(Date fechaInicioPublicacion) {
        this.fechaInicioPublicacion = fechaInicioPublicacion;
    }

    
    @Column(name="general", nullable=false, length=1)
    public char getGeneral() {
        return this.general;
    }
    
    public void setGeneral(char general) {
        this.general = general;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aviso")
    public Set<AvisoSeccion> getAvisoSeccions() {
        return this.avisoSeccions;
    }
    
    public void setAvisoSeccions(Set<AvisoSeccion> avisoSeccions) {
        this.avisoSeccions = avisoSeccions;
    }




}


