package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * AvisoSeccion generated by hbm2java
 */
@Entity
@Table(name="aviso_seccion"
)
public class AvisoSeccion  implements java.io.Serializable {


     private AvisoSeccionId id;
     private Seccion seccion;
     private Aviso aviso;

    public AvisoSeccion() {
    }

    public AvisoSeccion(AvisoSeccionId id, Seccion seccion, Aviso aviso) {
       this.id = id;
       this.seccion = seccion;
       this.aviso = aviso;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idAviso", column=@Column(name="id_aviso", nullable=false) ), 
        @AttributeOverride(name="idSeccion", column=@Column(name="id_seccion", nullable=false) ) } )
    @NotNull
    public AvisoSeccionId getId() {
        return this.id;
    }
    
    public void setId(AvisoSeccionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_seccion", nullable=false, insertable=false, updatable=false)
    @NotNull
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_aviso", nullable=false, insertable=false, updatable=false)
    @NotNull
    public Aviso getAviso() {
        return this.aviso;
    }
    
    public void setAviso(Aviso aviso) {
        this.aviso = aviso;
    }




}


