package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name="docente"
)
public class Docente  implements java.io.Serializable {


     private long idPersona;
     private Colegio colegio;
     private Persona persona;
     private Set<PeriodoAcademicoSeccionCurso> periodoAcademicoSeccionCursos = new HashSet<PeriodoAcademicoSeccionCurso>(0);

    public Docente() {
    }

	
    public Docente(Colegio colegio, Persona persona) {
        this.colegio = colegio;
        this.persona = persona;
    }
    public Docente(Colegio colegio, Persona persona, Set<PeriodoAcademicoSeccionCurso> periodoAcademicoSeccionCursos) {
       this.colegio = colegio;
       this.persona = persona;
       this.periodoAcademicoSeccionCursos = periodoAcademicoSeccionCursos;
    }
   
     //@GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="persona"))
    @Id 
    //@GeneratedValue(generator="generator")
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id_persona", unique=true, nullable=false)
    public long getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(long idPersona) {
        this.idPersona = idPersona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_colegio", nullable=false)
    @NotNull
    public Colegio getColegio() {
        return this.colegio;
    }
    
    public void setColegio(Colegio colegio) {
        this.colegio = colegio;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    @NotNull
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docente")
    public Set<PeriodoAcademicoSeccionCurso> getPeriodoAcademicoSeccionCursos() {
        return this.periodoAcademicoSeccionCursos;
    }
    
    public void setPeriodoAcademicoSeccionCursos(Set<PeriodoAcademicoSeccionCurso> periodoAcademicoSeccionCursos) {
        this.periodoAcademicoSeccionCursos = periodoAcademicoSeccionCursos;
    }




}


