package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * LibretaNotasSubperiodo generated by hbm2java
 */
@Entity
@Table(name="libreta_notas_subperiodo"
)
public class LibretaNotasSubperiodo  implements java.io.Serializable {


     private long idLibretaNotasSubperiodo;
     private Curso curso;
     private LibretaNotas libretaNotas;
     private SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso;
     private PeriodoAcademico periodoAcademico;
     private BigDecimal nota;

    public LibretaNotasSubperiodo() {
    }

    public LibretaNotasSubperiodo(long idLibretaNotasSubperiodo, Curso curso, LibretaNotas libretaNotas, SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso, PeriodoAcademico periodoAcademico, BigDecimal nota) {
       this.idLibretaNotasSubperiodo = idLibretaNotasSubperiodo;
       this.curso = curso;
       this.libretaNotas = libretaNotas;
       this.subPeriodoAcademicoSeccionCurso = subPeriodoAcademicoSeccionCurso;
       this.periodoAcademico = periodoAcademico;
       this.nota = nota;
    }
   
     @Id 

    
    @Column(name="id_libreta_notas_subperiodo", unique=true, nullable=false)
    public long getIdLibretaNotasSubperiodo() {
        return this.idLibretaNotasSubperiodo;
    }
    
    public void setIdLibretaNotasSubperiodo(long idLibretaNotasSubperiodo) {
        this.idLibretaNotasSubperiodo = idLibretaNotasSubperiodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_curso", nullable=false)
    @NotNull
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_libreta_notas", nullable=false)
    @NotNull
    public LibretaNotas getLibretaNotas() {
        return this.libretaNotas;
    }
    
    public void setLibretaNotas(LibretaNotas libretaNotas) {
        this.libretaNotas = libretaNotas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_periodo_academico_seccion_curso", nullable=false)
    @NotNull
    public SubPeriodoAcademicoSeccionCurso getSubPeriodoAcademicoSeccionCurso() {
        return this.subPeriodoAcademicoSeccionCurso;
    }
    
    public void setSubPeriodoAcademicoSeccionCurso(SubPeriodoAcademicoSeccionCurso subPeriodoAcademicoSeccionCurso) {
        this.subPeriodoAcademicoSeccionCurso = subPeriodoAcademicoSeccionCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_periodo", nullable=false)
    @NotNull
    public PeriodoAcademico getPeriodoAcademico() {
        return this.periodoAcademico;
    }
    
    public void setPeriodoAcademico(PeriodoAcademico periodoAcademico) {
        this.periodoAcademico = periodoAcademico;
    }

    
    @Column(name="nota", nullable=false, precision=4)
    @NotNull
    public BigDecimal getNota() {
        return this.nota;
    }
    
    public void setNota(BigDecimal nota) {
        this.nota = nota;
    }




}


