package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MaterialEvaluacionId generated by hbm2java
 */
@Embeddable
public class MaterialEvaluacionId  implements java.io.Serializable {


     private long idMaterial;
     private long idEvaluacion;

    public MaterialEvaluacionId() {
    }

    public MaterialEvaluacionId(long idMaterial, long idEvaluacion) {
       this.idMaterial = idMaterial;
       this.idEvaluacion = idEvaluacion;
    }
   


    @Column(name="id_material", nullable=false)
    public long getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(long idMaterial) {
        this.idMaterial = idMaterial;
    }


    @Column(name="id_evaluacion", nullable=false)
    public long getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(long idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MaterialEvaluacionId) ) return false;
		 MaterialEvaluacionId castOther = ( MaterialEvaluacionId ) other; 
         
		 return (this.getIdMaterial()==castOther.getIdMaterial())
 && (this.getIdEvaluacion()==castOther.getIdEvaluacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdMaterial();
         result = 37 * result + (int) this.getIdEvaluacion();
         return result;
   }   


}


