package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.AutoCreate;
import org.jboss.seam.annotations.Name;

/**
 * Materiales generated by hbm2java
 */
@Entity
@Table(name="materiales"
)
@Name("materiales")
@AutoCreate
public class Materiales  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1895297088290324460L;
	private long idMaterial;
     private RepositorioArchivos repositorioArchivos;
     private String nombreArchivo;
     private String descripcion;
     private Set<MaterialAsignacion> materialAsignacions = new HashSet<MaterialAsignacion>(0);
     private Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos = new HashSet<SubPeriodoAcademicoSeccionCurso>(0);
     private Set<PeriodoAcademicoSeccionCurso> periodoAcademicoSeccionCursos = new HashSet<PeriodoAcademicoSeccionCurso>(0);
     private Set<MaterialEvaluacion> materialEvaluacions = new HashSet<MaterialEvaluacion>(0);

    public Materiales() {
    }

	
    public Materiales(long idMaterial, RepositorioArchivos repositorioArchivos, String nombreArchivo, String descripcion) {
        this.idMaterial = idMaterial;
        this.repositorioArchivos = repositorioArchivos;
        this.nombreArchivo = nombreArchivo;
        this.descripcion = descripcion;
    }
    public Materiales(long idMaterial, RepositorioArchivos repositorioArchivos, String nombreArchivo, String descripcion, Set<MaterialAsignacion> materialAsignacions, Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos, Set<PeriodoAcademicoSeccionCurso> periodoAcademicoSeccionCursos, Set<MaterialEvaluacion> materialEvaluacions) {
       this.idMaterial = idMaterial;
       this.repositorioArchivos = repositorioArchivos;
       this.nombreArchivo = nombreArchivo;
       this.descripcion = descripcion;
       this.materialAsignacions = materialAsignacions;
       this.subPeriodoAcademicoSeccionCursos = subPeriodoAcademicoSeccionCursos;
       this.periodoAcademicoSeccionCursos = periodoAcademicoSeccionCursos;
       this.materialEvaluacions = materialEvaluacions;
    }
   
    @Id 
    @Column(name="id_material", unique=true, nullable=false)
    public long getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(long idMaterial) {
        this.idMaterial = idMaterial;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_repositorio", nullable=false)
    @NotNull
    public RepositorioArchivos getRepositorioArchivos() {
        return this.repositorioArchivos;
    }
    
    public void setRepositorioArchivos(RepositorioArchivos repositorioArchivos) {
        this.repositorioArchivos = repositorioArchivos;
    }

    
    @Column(name="nombre_archivo", nullable=false, length=50)
    @NotNull
    @Length(max=50)
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }
    
    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }

    
    @Column(name="descripcion", nullable=false, length=100)
    @NotNull
    @Length(max=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="materiales")
    public Set<MaterialAsignacion> getMaterialAsignacions() {
        return this.materialAsignacions;
    }
    
    public void setMaterialAsignacions(Set<MaterialAsignacion> materialAsignacions) {
        this.materialAsignacions = materialAsignacions;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="material_seccion_curso_sub_periodo", joinColumns = { 
        @JoinColumn(name="id_material", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_sub_periodo_academico_seccion_curso", nullable=false, updatable=false) })
    public Set<SubPeriodoAcademicoSeccionCurso> getSubPeriodoAcademicoSeccionCursos() {
        return this.subPeriodoAcademicoSeccionCursos;
    }
    
    public void setSubPeriodoAcademicoSeccionCursos(Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos) {
        this.subPeriodoAcademicoSeccionCursos = subPeriodoAcademicoSeccionCursos;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="materialeses")
    public Set<PeriodoAcademicoSeccionCurso> getPeriodoAcademicoSeccionCursos() {
        return this.periodoAcademicoSeccionCursos;
    }
    
    public void setPeriodoAcademicoSeccionCursos(Set<PeriodoAcademicoSeccionCurso> periodoAcademicoSeccionCursos) {
        this.periodoAcademicoSeccionCursos = periodoAcademicoSeccionCursos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="materiales")
    public Set<MaterialEvaluacion> getMaterialEvaluacions() {
        return this.materialEvaluacions;
    }
    
    public void setMaterialEvaluacions(Set<MaterialEvaluacion> materialEvaluacions) {
        this.materialEvaluacions = materialEvaluacions;
    }




}


