package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * MedioContacto generated by hbm2java
 */
@Entity
@Table(name="medio_contacto"
)
public class MedioContacto  implements java.io.Serializable {


     private int idMedioContacto;
     private String nombre;
     private Set<PersonaMedioContacto> personaMedioContactos = new HashSet<PersonaMedioContacto>(0);
     private Set<ColegioMedioContacto> colegioMedioContactos = new HashSet<ColegioMedioContacto>(0);

    public MedioContacto() {
    }

	
    public MedioContacto(int idMedioContacto, String nombre) {
        this.idMedioContacto = idMedioContacto;
        this.nombre = nombre;
    }
    public MedioContacto(int idMedioContacto, String nombre, Set<PersonaMedioContacto> personaMedioContactos, Set<ColegioMedioContacto> colegioMedioContactos) {
       this.idMedioContacto = idMedioContacto;
       this.nombre = nombre;
       this.personaMedioContactos = personaMedioContactos;
       this.colegioMedioContactos = colegioMedioContactos;
    }
   
     @Id 

    
    @Column(name="id_medio_contacto", unique=true, nullable=false)
    public int getIdMedioContacto() {
        return this.idMedioContacto;
    }
    
    public void setIdMedioContacto(int idMedioContacto) {
        this.idMedioContacto = idMedioContacto;
    }

    
    @Column(name="nombre", nullable=false)
    @NotNull
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medioContacto")
    public Set<PersonaMedioContacto> getPersonaMedioContactos() {
        return this.personaMedioContactos;
    }
    
    public void setPersonaMedioContactos(Set<PersonaMedioContacto> personaMedioContactos) {
        this.personaMedioContactos = personaMedioContactos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medioContacto")
    public Set<ColegioMedioContacto> getColegioMedioContactos() {
        return this.colegioMedioContactos;
    }
    
    public void setColegioMedioContactos(Set<ColegioMedioContacto> colegioMedioContactos) {
        this.colegioMedioContactos = colegioMedioContactos;
    }




}


