package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * MensajeDestinatario generated by hbm2java
 */
@Entity
@Table(name="mensaje_destinatario"
)
public class MensajeDestinatario  implements java.io.Serializable {


     private MensajeDestinatarioId id;
     private Persona persona;
     private Mensaje mensaje;

    public MensajeDestinatario() {
    }

    public MensajeDestinatario(MensajeDestinatarioId id, Persona persona, Mensaje mensaje) {
       this.id = id;
       this.persona = persona;
       this.mensaje = mensaje;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idMensaje", column=@Column(name="id_mensaje", nullable=false) ), 
        @AttributeOverride(name="idPersona", column=@Column(name="id_persona", nullable=false) ) } )
    @NotNull
    public MensajeDestinatarioId getId() {
        return this.id;
    }
    
    public void setId(MensajeDestinatarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_persona", nullable=false, insertable=false, updatable=false)
    @NotNull
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mensaje", nullable=false, insertable=false, updatable=false)
    @NotNull
    public Mensaje getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(Mensaje mensaje) {
        this.mensaje = mensaje;
    }




}


