package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Moneda generated by hbm2java
 */
@Entity
@Table(name="moneda"
)
public class Moneda  implements java.io.Serializable {


     private long idMoneda;
     private String nombre;
     private String codigo;
     private Set<ReciboPension> reciboPensions = new HashSet<ReciboPension>(0);
     private Set<Colegio> colegios = new HashSet<Colegio>(0);

    public Moneda() {
    }

	
    public Moneda(long idMoneda, String nombre, String codigo) {
        this.idMoneda = idMoneda;
        this.nombre = nombre;
        this.codigo = codigo;
    }
    public Moneda(long idMoneda, String nombre, String codigo, Set<ReciboPension> reciboPensions, Set<Colegio> colegios) {
       this.idMoneda = idMoneda;
       this.nombre = nombre;
       this.codigo = codigo;
       this.reciboPensions = reciboPensions;
       this.colegios = colegios;
    }
   
     @Id 

    
    @Column(name="id_moneda", unique=true, nullable=false)
    public long getIdMoneda() {
        return this.idMoneda;
    }
    
    public void setIdMoneda(long idMoneda) {
        this.idMoneda = idMoneda;
    }

    
    @Column(name="nombre", nullable=false, length=20)
    @NotNull
    @Length(max=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="codigo", nullable=false, length=10)
    @NotNull
    @Length(max=10)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="moneda")
    public Set<ReciboPension> getReciboPensions() {
        return this.reciboPensions;
    }
    
    public void setReciboPensions(Set<ReciboPension> reciboPensions) {
        this.reciboPensions = reciboPensions;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="monedas")
    public Set<Colegio> getColegios() {
        return this.colegios;
    }
    
    public void setColegios(Set<Colegio> colegios) {
        this.colegios = colegios;
    }




}


