package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PeriodoAcademicoSeccionCurso generated by hbm2java
 */
@Entity
@Table(name="periodo_academico_seccion_curso"
)
public class PeriodoAcademicoSeccionCurso  implements java.io.Serializable {


     private long idPeriodoAcademicoSeccionCurso;
     private PeriodoAcademicoSeccion periodoAcademicoSeccion;
     private Seccion seccion;
     private Curso curso;
     private Docente docente;
     private String formulaNotaFinal;
     private Set<LibretaNotasFinalesCurso> libretaNotasFinalesCursos = new HashSet<LibretaNotasFinalesCurso>(0);
     private Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos = new HashSet<SubPeriodoAcademicoSeccionCurso>(0);
     private Set<PeriodoAcademicoSeccionCursoNota> periodoAcademicoSeccionCursoNotas = new HashSet<PeriodoAcademicoSeccionCursoNota>(0);
     private Set<Materiales> materialeses = new HashSet<Materiales>(0);

    public PeriodoAcademicoSeccionCurso() {
    }

	
    public PeriodoAcademicoSeccionCurso(long idPeriodoAcademicoSeccionCurso, PeriodoAcademicoSeccion periodoAcademicoSeccion, Seccion seccion, Curso curso, Docente docente) {
        this.idPeriodoAcademicoSeccionCurso = idPeriodoAcademicoSeccionCurso;
        this.periodoAcademicoSeccion = periodoAcademicoSeccion;
        this.seccion = seccion;
        this.curso = curso;
        this.docente = docente;
    }
    public PeriodoAcademicoSeccionCurso(long idPeriodoAcademicoSeccionCurso, PeriodoAcademicoSeccion periodoAcademicoSeccion, Seccion seccion, Curso curso, Docente docente, String formulaNotaFinal, Set<LibretaNotasFinalesCurso> libretaNotasFinalesCursos, Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos, Set<PeriodoAcademicoSeccionCursoNota> periodoAcademicoSeccionCursoNotas, Set<Materiales> materialeses) {
       this.idPeriodoAcademicoSeccionCurso = idPeriodoAcademicoSeccionCurso;
       this.periodoAcademicoSeccion = periodoAcademicoSeccion;
       this.seccion = seccion;
       this.curso = curso;
       this.docente = docente;
       this.formulaNotaFinal = formulaNotaFinal;
       this.libretaNotasFinalesCursos = libretaNotasFinalesCursos;
       this.subPeriodoAcademicoSeccionCursos = subPeriodoAcademicoSeccionCursos;
       this.periodoAcademicoSeccionCursoNotas = periodoAcademicoSeccionCursoNotas;
       this.materialeses = materialeses;
    }
   
    @Id  
    @Column(name="id_periodo_academico_seccion_curso", unique=true, nullable=false)
    public long getIdPeriodoAcademicoSeccionCurso() {
        return this.idPeriodoAcademicoSeccionCurso;
    }
    
    public void setIdPeriodoAcademicoSeccionCurso(long idPeriodoAcademicoSeccionCurso) {
        this.idPeriodoAcademicoSeccionCurso = idPeriodoAcademicoSeccionCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_periodo_academico_seccion", nullable=false)
    @NotNull
    public PeriodoAcademicoSeccion getPeriodoAcademicoSeccion() {
        return this.periodoAcademicoSeccion;
    }
    
    public void setPeriodoAcademicoSeccion(PeriodoAcademicoSeccion periodoAcademicoSeccion) {
        this.periodoAcademicoSeccion = periodoAcademicoSeccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_seccion", nullable=false)
    @NotNull
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_curso", nullable=false)
    @NotNull
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_docente", nullable=false)
    @NotNull
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }

    
    @Column(name="formula_nota_final", length=50)
    @Length(max=50)
    public String getFormulaNotaFinal() {
        return this.formulaNotaFinal;
    }
    
    public void setFormulaNotaFinal(String formulaNotaFinal) {
        this.formulaNotaFinal = formulaNotaFinal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademicoSeccionCurso")
    public Set<LibretaNotasFinalesCurso> getLibretaNotasFinalesCursos() {
        return this.libretaNotasFinalesCursos;
    }
    
    public void setLibretaNotasFinalesCursos(Set<LibretaNotasFinalesCurso> libretaNotasFinalesCursos) {
        this.libretaNotasFinalesCursos = libretaNotasFinalesCursos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademicoSeccionCurso")
    public Set<SubPeriodoAcademicoSeccionCurso> getSubPeriodoAcademicoSeccionCursos() {
        return this.subPeriodoAcademicoSeccionCursos;
    }
    
    public void setSubPeriodoAcademicoSeccionCursos(Set<SubPeriodoAcademicoSeccionCurso> subPeriodoAcademicoSeccionCursos) {
        this.subPeriodoAcademicoSeccionCursos = subPeriodoAcademicoSeccionCursos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodoAcademicoSeccionCurso")
    public Set<PeriodoAcademicoSeccionCursoNota> getPeriodoAcademicoSeccionCursoNotas() {
        return this.periodoAcademicoSeccionCursoNotas;
    }
    
    public void setPeriodoAcademicoSeccionCursoNotas(Set<PeriodoAcademicoSeccionCursoNota> periodoAcademicoSeccionCursoNotas) {
        this.periodoAcademicoSeccionCursoNotas = periodoAcademicoSeccionCursoNotas;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="material_seccion_curso_periodo", joinColumns = { 
        @JoinColumn(name="id_periodo_academico_seccion_curso", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_material", nullable=false, updatable=false) })
    public Set<Materiales> getMaterialeses() {
        return this.materialeses;
    }
    
    public void setMaterialeses(Set<Materiales> materialeses) {
        this.materialeses = materialeses;
    }




}


