package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * PeriodoAcademicoSeccionCursoNota generated by hbm2java
 */
@Entity
@Table(name="periodo_academico_seccion_curso_nota"
)
public class PeriodoAcademicoSeccionCursoNota  implements java.io.Serializable {


     private long idPersona;
     private Alumno alumno;
     private PeriodoAcademicoSeccionCurso periodoAcademicoSeccionCurso;
     private BigDecimal notaFinalCurso;

    public PeriodoAcademicoSeccionCursoNota() {
    }

    public PeriodoAcademicoSeccionCursoNota(Alumno alumno, PeriodoAcademicoSeccionCurso periodoAcademicoSeccionCurso, BigDecimal notaFinalCurso) {
       this.alumno = alumno;
       this.periodoAcademicoSeccionCurso = periodoAcademicoSeccionCurso;
       this.notaFinalCurso = notaFinalCurso;
    }
   
     //@GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="alumno"))
    @Id 
    //@GeneratedValue(generator="generator")
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id_persona", unique=true, nullable=false)
    public long getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(long idPersona) {
        this.idPersona = idPersona;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    @NotNull
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_periodo_academico_seccion_curso", nullable=false)
    @NotNull
    public PeriodoAcademicoSeccionCurso getPeriodoAcademicoSeccionCurso() {
        return this.periodoAcademicoSeccionCurso;
    }
    
    public void setPeriodoAcademicoSeccionCurso(PeriodoAcademicoSeccionCurso periodoAcademicoSeccionCurso) {
        this.periodoAcademicoSeccionCurso = periodoAcademicoSeccionCurso;
    }

    
    @Column(name="nota_final_curso", nullable=false, precision=2)
    @NotNull
    public BigDecimal getNotaFinalCurso() {
        return this.notaFinalCurso;
    }
    
    public void setNotaFinalCurso(BigDecimal notaFinalCurso) {
        this.notaFinalCurso = notaFinalCurso;
    }




}


