package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * RepositorioArchivos generated by hbm2java
 */
@Entity
@Table(name="repositorio_archivos"
)
public class RepositorioArchivos  implements java.io.Serializable {


     private int idRepositorio;
     private Colegio colegio;
     private String url;
     private Set<Materiales> materialeses = new HashSet<Materiales>(0);
     private Set<FotoPersona> fotoPersonas = new HashSet<FotoPersona>(0);

    public RepositorioArchivos() {
    }

	
    public RepositorioArchivos(int idRepositorio, Colegio colegio, String url) {
        this.idRepositorio = idRepositorio;
        this.colegio = colegio;
        this.url = url;
    }
    public RepositorioArchivos(int idRepositorio, Colegio colegio, String url, Set<Materiales> materialeses, Set<FotoPersona> fotoPersonas) {
       this.idRepositorio = idRepositorio;
       this.colegio = colegio;
       this.url = url;
       this.materialeses = materialeses;
       this.fotoPersonas = fotoPersonas;
    }
   
     @Id 

    
    @Column(name="id_repositorio", unique=true, nullable=false)
    public int getIdRepositorio() {
        return this.idRepositorio;
    }
    
    public void setIdRepositorio(int idRepositorio) {
        this.idRepositorio = idRepositorio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_colegio", nullable=false)
    @NotNull
    public Colegio getColegio() {
        return this.colegio;
    }
    
    public void setColegio(Colegio colegio) {
        this.colegio = colegio;
    }

    
    @Column(name="url", nullable=false, length=60)
    @NotNull
    @Length(max=60)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="repositorioArchivos")
    public Set<Materiales> getMaterialeses() {
        return this.materialeses;
    }
    
    public void setMaterialeses(Set<Materiales> materialeses) {
        this.materialeses = materialeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="repositorioArchivos")
    public Set<FotoPersona> getFotoPersonas() {
        return this.fotoPersonas;
    }
    
    public void setFotoPersonas(Set<FotoPersona> fotoPersonas) {
        this.fotoPersonas = fotoPersonas;
    }




}


