package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResumenAlumnoId generated by hbm2java
 */
@Embeddable
public class ResumenAlumnoId  implements java.io.Serializable {


     private long idPeriodoAcademico;
     private long idPersona;

    public ResumenAlumnoId() {
    }

    public ResumenAlumnoId(long idPeriodoAcademico, long idPersona) {
       this.idPeriodoAcademico = idPeriodoAcademico;
       this.idPersona = idPersona;
    }
   


    @Column(name="id_periodo_academico", nullable=false)
    public long getIdPeriodoAcademico() {
        return this.idPeriodoAcademico;
    }
    
    public void setIdPeriodoAcademico(long idPeriodoAcademico) {
        this.idPeriodoAcademico = idPeriodoAcademico;
    }


    @Column(name="id_persona", nullable=false)
    public long getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(long idPersona) {
        this.idPersona = idPersona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ResumenAlumnoId) ) return false;
		 ResumenAlumnoId castOther = ( ResumenAlumnoId ) other; 
         
		 return (this.getIdPeriodoAcademico()==castOther.getIdPeriodoAcademico())
 && (this.getIdPersona()==castOther.getIdPersona());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdPeriodoAcademico();
         result = 37 * result + (int) this.getIdPersona();
         return result;
   }   


}


