package org.domain.colegium.entity;
// Generated Mar 13, 2012 10:24:56 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ResumenAlumno generated by hbm2java
 */
@Entity
@Table(name="resumen_alumno"
)
public class ResumenAlumno  implements java.io.Serializable {


     private ResumenAlumnoId id;
     private Seccion seccion;
     private Colegio colegio;
     private Alumno alumno;
     private PeriodoAcademico periodoAcademico;
     private Grado grado;

    public ResumenAlumno() {
    }

    public ResumenAlumno(ResumenAlumnoId id, Seccion seccion, Colegio colegio, Alumno alumno, PeriodoAcademico periodoAcademico, Grado grado) {
       this.id = id;
       this.seccion = seccion;
       this.colegio = colegio;
       this.alumno = alumno;
       this.periodoAcademico = periodoAcademico;
       this.grado = grado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPeriodoAcademico", column=@Column(name="id_periodo_academico", nullable=false) ), 
        @AttributeOverride(name="idPersona", column=@Column(name="id_persona", nullable=false) ) } )
    @NotNull
    public ResumenAlumnoId getId() {
        return this.id;
    }
    
    public void setId(ResumenAlumnoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_seccion", nullable=false)
    @NotNull
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_colegio", nullable=false)
    @NotNull
    public Colegio getColegio() {
        return this.colegio;
    }
    
    public void setColegio(Colegio colegio) {
        this.colegio = colegio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_persona", nullable=false, insertable=false, updatable=false)
    @NotNull
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_periodo_academico", nullable=false, insertable=false, updatable=false)
    @NotNull
    public PeriodoAcademico getPeriodoAcademico() {
        return this.periodoAcademico;
    }
    
    public void setPeriodoAcademico(PeriodoAcademico periodoAcademico) {
        this.periodoAcademico = periodoAcademico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_grado", nullable=false)
    @NotNull
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }




}


